### ISSUE TITLE
Uncaught Error: spawn EN0ENT

### ISSUE THREAD

**Issue by elsmorian** [AtomLinter/linter-flake8#1]
When this package is installed, the console fills up with:

`Uncaught Error: spawn ENOENT util.js:682
exports._errnoException util.js:682
ChildProcess._handle.onexit child_process.js:857
(anonymous function) child_process.js:1005
_tickCallback`

Seemingly every time it tries to lint. There is no linking feedback on the UI.

I narrowed it down to this package- disabling it stops these messages.

I installed flake9 as per the README, and my terminal can find it no problem, but just incase I tried explicitly stating `/usr/local/bin` as the executable dir but this does not help.

Atom 0.117.0 OSX 10.9.4

Let me know if I can provide any more info!

**Comment by StanislavGlebik** [comment]
Hey.
I have similar problem.
My .cson:
 33   "linter-flake8":
 34     executableDir: "/usr/local/bin"

which flake8
/usr/local/bin/flake8

ls -al /usr/local/bin/flake8
-rwxr-xr-x  1 stash  admin  212 May  6 13:39 /usr/local/bin/flake8

Is there anything else I can try?

**Comment by StanislavGlebik** [comment]
Oh, and I'm working with remote project folder

**Comment by Arcanemagus** [comment]
@StanislavGlebik please open a new issue, no reason to necro this ancient one :stuck_out_tongue:.
