### ISSUE TITLE
Exception when code is folded

### ISSUE THREAD

**Issue by frasergraham** [AtomLinter/linter-flake8#101]
Whenever I have any code folded I get this exception during saving, it was working fine after i updated the plugin this morning and it works again now that I restarted Atom, but I was hitting this consistently for a while...

TypeError: Cannot read property 'tokens' of undefined
TypeError: Cannot read property 'tokens' of undefined
  at extractRange (/Users/fraser/.atom/packages/linter-flake8/lib/main.coffee:58:28)
  at /Users/fraser/.atom/packages/linter-flake8/lib/main.coffee:167:22
  at process._tickCallback (node.js:365:9)

**Comment by Arcanemagus** [comment]
Are you saying you were seeing this after updating to v1.9.1? (And just for good measure a restart of Atom)

**Comment by Arcanemagus** [comment]
(This was reported initially in #97 and fixed in #98)

**Comment by frasergraham** [comment]
I updated this morning to the latest, I saw this after that but i do not believe I restarted Atom after updating.

**Comment by Arcanemagus** [comment]
Atom is odd sometimes about updating packages, it _should_ be good without a restart but lately I've noticed it hasn't been updating packages till after restarting. I'm going to mark this as closed but if you are still seeing this please let me know, especially with a stack trace if possible.
