### ISSUE TITLE
Incorrect catch of E712 (comparison to False) in function arguments

### ISSUE THREAD

**Issue by lzkelley** [AtomLinter/linter-flake8#102]
For an array of boolean values `valid`, if I want to find the `False` elements I might use something like:

    badInds = numpy.where(valid == False)

`Flake8` itself recognizes this as valid (running from the command-line), but `linter-flake8` shows the error `E712 - comparison to False should be 'if cond is False:' or 'if not cond:'` which will break this statement.

**Comment by Arcanemagus** [comment]
`linter-flake8` simply runs `flake8`, parses the results, and passes the messages on to `linter`. Are you sure that the version of `flake8` that you are running on the command line and the one that Atom is finding are the same?

Try running Atom from the same prompt you test that from, and making sure you don't have a hard coded path to a different version of `flake8` in your settings.

**Comment by lzkelley** [comment]
Weird, yeah - now that I'm being sure to use the same version --- it is showing up in the command line as-well.  I'll take to `flake8`... sorry about the mis-issue.

**Comment by Arcanemagus** [comment]
No worries :wink:.
