### ISSUE TITLE
Add --exit-zero to flake8 invocation

### ISSUE THREAD

**Issue by ficoos** [AtomLinter/linter-flake8#105]
Without it, if there is an intermediate sate where flake8 can't parse the file errors start popping up and you need to manually close them,

**Comment by schlamar** [comment]
> manually close them

Do you mean flake8 processes? Because I have the issue that there are sometimes flake8 zombie subprocesses. Not sure if this is the same issue:

![flake8](https://cloud.githubusercontent.com/assets/238652/11272730/4f88d4a4-8ecf-11e5-9bd0-756083565a8d.PNG)

**Comment by Arcanemagus** [comment]
Do you have steps to reproduce this? From the description of the flag that just changes the exit code, not any actual behavior.

**Comment by Arcanemagus** [comment]
@ficoos @schlamar Any updates?

**Comment by Arcanemagus** [comment]
Just dug through the [`flake8` code](https://github.com/PyCQA/flake8/blob/ac87e2d71ead7a37696a59d094432350cea96918/flake8/main.py#L50), as I suspected all that does is change the exit value to `0` even if it finds errors.

I think the proper solution to this is to track spawned executables and hold off on linting (or kill the old one) when a new lint is requested.

**Comment by Arcanemagus** [comment]
Marking this as closed as what it requests has no bearing on the real issue. I've filed #117 to track what I believe to be the solution to this.
