### ISSUE TITLE
Flake8 errors keep coming up just installed 

### ISSUE THREAD

**Issue by andela-unkwocha** [AtomLinter/linter-flake8#106]
Hi, I just recently installed atom and installed Linter,
following the instructions here http://www.marinamele.com/install-and-configure-atom-editor-for-python
![screen shot 2015-11-06 at 12 18 23 pm](https://cloud.githubusercontent.com/assets/3197630/10995890/904d7138-8480-11e5-8452-88c4d9bc946d.png)
 flake8 following the instructions, but I keep gettng error on the side of the screen.
I use a Mac

**Comment by Arcanemagus** [comment]
Looks like you probably installed the latest version of `pep257` and are using `flake8-pep257`. Unfortunately that hasn't been updated to be compatible yet, you can try uninstalling that and using `flake8-docstrings` which gives you the same functionality.

Marking as closed as this isn't an issue with `linter-flake8`, feel free to keep commenting here though.

**Comment by cemsbr** [comment]
I also had this problem. I've just made a pull request to remove flake8-pep257 from documentation.

**Comment by mandel01** [comment]
I newly installed `linter-flake8` today on Max OSX. I received a number of errors that I eventually was able to resolve by upgrading the `flake8-docstrings` (see details below). I expected the problem to be an issue with my PATH (relating to Anaconda) or an issue with not using a virtual environment as recommended in the README. However, I found this closed issue. My errors were very similar the ones above. I had just installed `pip install flake8-docstrings` (on a recently formatted hard drive) so I did not expect that to be the issue, but upon upgrading with `pip install flake8-docstrings --upgrade` the errors disappeared and the linter works perfectly! I am all set; this is just FYI in case others encounter this problem...

first linter-flake8 error:
```
Error: Traceback (most recent call last): File "/Users/markmandel/anaconda/bin/flake8", line 11, in sys.exit(main()) File "/Users/markmandel/anaconda/lib/python3.5/site-packages/flake8/main.py", line 32, in main report = flake8_style.check_files() File "/Users/markmandel/anaconda/lib/python3.5/site-packages/pep8.py", line 1672, in check_files runner(path) File "/Users/markmandel/anaconda/lib/python3.5/site-packages/flake8/engine.py", line 99, in input_file return fchecker.check_all(expected=expected, line_offset=line_offset) File "/Users/markmandel/anaconda/lib/python3.5/site-packages/pep8.py", line 1412, in check_all self.check_ast() File "/Users/markmandel/anaconda/lib/python3.5/site-packages/pep8.py", line 1358, in check_ast checker = cls(tree, self.filename) File "/Users/markmandel/anaconda/lib/python3.5/site-packages/flake8_docstrings.py", line 28, in init self.load_source() File "/Users/markmandel/anaconda/lib/python3.5/site-packages/flake8_docstrings.py", line 43, in load_source self.source = pep8.stdin_get_value() File "/Users/markmandel/anaconda/lib/python3.5/site-packages/pep8.py", line 1060, in stdin_get_value return TextIOWrapper(sys.stdin.buffer, errors='ignore').read() ValueError: I/O operation on closed file
```

upgrade of flake8-docstrings:

```
dmi-mbpro2-mandel:test markmandel$ pip install flake8-docstrings
Requirement already satisfied (use --upgrade to upgrade): flake8-docstrings in /Users/markmandel/anaconda/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): flake8 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8-docstrings)
Requirement already satisfied (use --upgrade to upgrade): pep257 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8-docstrings)
Requirement already satisfied (use --upgrade to upgrade): mccabe>=0.2.1 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8->flake8-docstrings)
Requirement already satisfied (use --upgrade to upgrade): pyflakes>=0.8.1 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8->flake8-docstrings)
Requirement already satisfied (use --upgrade to upgrade): pep8>=1.5.7 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8->flake8-docstrings)
dmi-mbpro2-mandel:test markmandel$ pip install flake8-docstrings --upgrade
Requirement already up-to-date: flake8-docstrings in /Users/markmandel/anaconda/lib/python3.5/site-packages
Collecting flake8 (from flake8-docstrings)
  Using cached flake8-2.5.1-py2.py3-none-any.whl
Requirement already up-to-date: pep257 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8-docstrings)
Collecting mccabe<0.4,>=0.2.1 (from flake8->flake8-docstrings)
  Using cached mccabe-0.3.1-py2.py3-none-any.whl
Requirement already up-to-date: pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 in /Users/markmandel/anaconda/lib/python3.5/site-packages (from flake8->flake8-docstrings)
Collecting pyflakes<1.1,>=0.8.1 (from flake8->flake8-docstrings)
  Downloading pyflakes-1.0.0-py2.py3-none-any.whl (152kB)
    100% |████████████████████████████████| 155kB 2.1MB/s 
Installing collected packages: mccabe, pyflakes, flake8
  Found existing installation: mccabe 0.2.1
    Uninstalling mccabe-0.2.1:
      Successfully uninstalled mccabe-0.2.1
  Found existing installation: pyflakes 0.8.1
    Uninstalling pyflakes-0.8.1:
      Successfully uninstalled pyflakes-0.8.1
  Found existing installation: flake8 2.2.4
    Uninstalling flake8-2.2.4:
      Successfully uninstalled flake8-2.2.4
Successfully installed flake8-2.5.1 mccabe-0.3.1 pyflakes-1.0.0

```

**Comment by Arcanemagus** [comment]
Glad you got it figured out @mandel01 :wink:.

**Comment by mandel01** [comment]
Thanks for the great tool, but it seems that I wrote too soon. After 10-15 minutes the errors return. The linter continues to work even with the messages there, and I can quench them (for another 10-15 minutes) by restarting Atom. Any ideas?

![2015-12-30-12-42-00-screenshot](https://cloud.githubusercontent.com/assets/8669125/12055750/b74e5370-aef5-11e5-9096-4f0614523018.png)

**Comment by Arcanemagus** [comment]
When that error shows up can you run `flake8` on the file from a terminal? That seems to be a crash in `flake8` being forwarded on.

**Comment by mandel01** [comment]
No problems for 24 hours :) If it comes back and I can't figure it out I'll post something. Thanks @Arcanemagus for the input!
