### ISSUE TITLE
Can't highlight unnecessary imports when using MagicPython syntax.

### ISSUE THREAD

**Issue by mythmon** [AtomLinter/linter-flake8#107]
I'm not sure which package is at fault, but when using the MagicStack/MagicPython syntax pack, unnecessary imports are highlighted at the end of the file instead of in the correct place.

I also filed MagicStack/MagicPython/issues/24.

**Comment by Arcanemagus** [comment]
This looks to be fixed on their end from the status of the linked issue, marking as closed.
