### ISSUE TITLE
Warnings / Errors sporadically not updating

### ISSUE THREAD

**Issue by lzkelley** [AtomLinter/linter-flake8#111]
Often (but sporadically) certain warnings and errors aren't updated to reflect that they are no longer present.  For example, *`F841 - local variable '<VARNAME>` is assigned to but never used`*, will remain even after that variable *is definitely* being used.  

Work-arounds:
-   Closing the open window/buffer and reopening it fixes the problem.
-   Cutting and pasting the line causing the error seems to force a re-check, and fixes the problem.

It seems like there is some underlying bug causing flake8 not to be updated, or for previous warnings not to be erased.

**Comment by Arcanemagus** [comment]
This would be an issue with `linter` or far less likely `flake8`, not `linter-flake8`. (I've seen this occasionally to from a variety of providers.

Marking as closed but please file an issue on `linter` about this if there isn't one already.
