### ISSUE TITLE
pep257 is not working

### ISSUE THREAD

**Issue by cemsbr** [AtomLinter/linter-flake8#112]
I can't see pep257 messages in atom. However, I can see syntax errors and also mccabe warnings.
```
$ flake8 asyncshell/executor.py
asyncshell/executor.py:1:1: D100  Missing docstring in public module
$ flake8 --version
2.5.0 (pep8: 1.6.2, mccabe: 0.3.1, pyflakes: 1.0.0, pep257: 0.2.1.post1) CPython 3.5.0 on Linux
$ pip search flake8-docstrings | grep flake8-docstrings -A1 | tail -n 1
  INSTALLED: 0.2.1.post1 (latest)
```

**Comment by Arcanemagus** [comment]
Well as @steelbrain already pointed out, this _should_ be working, although the RegEx he used was out of date. It should be being recognized with the current one: https://regex101.com/r/sD2kT8/2

Can you open Developer Tools and put a breakpoint on [this line](https://github.com/AtomLinter/linter-flake8/blob/master/lib/main.coffee#L173) and see what the match looks like?

**Comment by cemsbr** [comment]
This line is not executed because result is empty. I'm trying to debug why.

**Comment by cemsbr** [comment]
I found out what is happening. This linter makes flake8 read from stdin and, unfortunatley, flake8-docstrings is not working with stdin, as discussed in this [bug report](https://gitlab.com/pycqa/flake8-docstrings/issues/2). By the way, @Arcanemagus created it!

So, we must wait for that bug to be solved, solve it or make flake8 read the file by its path. Maybe I'm missing some other solution.

**Comment by Arcanemagus** [comment]
I knew there was a reason I preferred `flake8-pep257`....

**Comment by cemsbr** [comment]
Yes, I forgot this other option (support flake8-pep257). By now, I'm using linter-pep257.

**Comment by Arcanemagus** [comment]
Marking this as closed since it isn't an issue with `linter-flake8` and there is a workaround available. Also pinged the `flake8-docstrings` author again :wink:.
