### ISSUE TITLE
Leaving "Max complexity" default settings overwrite configuration file

### ISSUE THREAD

**Issue by socketubs** [AtomLinter/linter-flake8#121]
Hi there,

If I don't set a `Max complexity` setting, `linter-flake8` will always execute `flake8` with `--max-complexity 10` which will overwrite my configuration file (setted in settings as `Project file` or automatically detected by flake8).

Default flake8 command line doesn't run any complexity checks.
I think, `linter-flake8` must be as close as possible to default flake8 settings which is not the case today because there is a default `Max complexity` setted at 10.

Workaround to mimic flake8 default which is to set `Max complexity` to `-1`.

**Comment by Arcanemagus** [comment]
Sounds perfectly reasonable to me, do you want to submit a PR that changes the default value?

**Comment by socketubs** [comment]
@Arcanemagus, Of course I'll. :smile_cat:
