### ISSUE TITLE
Underline mispositionned

### ISSUE THREAD

**Issue by ugomeda** [AtomLinter/linter-flake8#126]
I have this issue where linter-flake8 underlines the wrong part of a line :

```
flake8 backend/views/store.py
backend/views/store.py:50:26: F821 undefined name 'uuid'
```

And yet, characters 15-19 (instead of 26-30) are underlined, see the attached file :
![screenshot from 2015-12-15 10-37-27](https://cloud.githubusercontent.com/assets/932339/11807112/022580f6-a318-11e5-8928-c3aa6f898b11.png)

**Comment by Arcanemagus** [comment]
@patrys looks like this is another issue in your code that attempts to get smart highlighting, do you have time to look over that (and #99 while you are at it :stuck_out_tongue:)?

**Comment by patrys** [comment]
Sure, I'll work on a fix.

**Comment by ugomeda** [comment]
Thanks !

**Comment by Arcanemagus** [comment]
v1.9.3 has been published that includes this fix, please let us know if you see any more issues.

**Comment by ugomeda** [comment]
I'm reopening this issue, this happened with version 1.9.3 :

![screenshot from 2016-01-14 10-04-58](https://cloud.githubusercontent.com/assets/932339/12320045/95057d36-baa6-11e5-9a50-82810b4914e8.png)

Output of Flake8 (it's putting the error on the "from" sadly) :

```
malice_controller/tasks/utils.py:2:1: F401 'db' imported but unused
```

Maybe for a F401, find a match after the ```import``` ?

**Comment by jminuscula** [comment]
This is happening to me again in v2.0.2 —maybe I'm missing something?

```
$ apm list | grep linter-flake8
├── linter-flake8@2.0.2

$ flake8 --version
3.0.4 (pycodestyle: 2.0.0, mccabe: 0.5.2, pyflakes: 1.2.3) CPython 3.5.1 on Darwin
```

![linter-flake8](https://cloud.githubusercontent.com/assets/209764/19719308/a7ef4978-9b69-11e6-981e-985660427f21.png)

**Comment by Arcanemagus** [comment]
@jminuscula Can you please file a new issue, including the output that `flake8` is giving you?
