### ISSUE TITLE
flake8 throw an error

### ISSUE THREAD

**Issue by faceair** [AtomLinter/linter-flake8#133]
![image](https://cloud.githubusercontent.com/assets/3659110/12032351/5176ce2c-ae52-11e5-83f4-c77c6ef9a9c0.png)

flake8 throw an error when i add `\` in the new line.
![image](https://cloud.githubusercontent.com/assets/3659110/12032365/7c728e72-ae52-11e5-8b61-69961309d2ae.png)

**Comment by Arcanemagus** [comment]
This is a `flake8` issue, not related to `linter-flake8`.

Do you see the same error when running `flake8` on that file from the terminal? Did you by any chance update `pep8` past v1.5.7? I'm pretty sure that is the stack trace that you get from later versions.

I'm marking this as closed, but feel free to keep posting if you have any further questions or information.
