### ISSUE TITLE
Why does print(foo, end='') throw a syntax error?

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-flake8#134]
This is valid syntax right? https://docs.python.org/3/library/functions.html#print

Is Flake8 only for Python 2 or something?

**Comment by Arcanemagus** [comment]
`flake8` changes it's validation rules based on the `python` it is running under, are you sure that the `flake8` Atom is running is running under a Python 3 environment?

**Comment by corysimmons** [comment]
Ah okay. Do you happen to know how to install flake8 under Python 3?

**Comment by Arcanemagus** [comment]
As far as I understand you simply run `flake8` in an environment where `python` executes the Python 3 version. This is where virtualenv can come in handy.

**Comment by corysimmons** [comment]
alright thanks
