### ISSUE TITLE
Error: pyenv: flake8: command not found

### ISSUE THREAD

**Issue by delta2323** [AtomLinter/linter-flake8#137]
Hi. I was trying using linter-flake8 in El Capitan(10.11.1) and encountered the following error. I personaly use pyenv and pyenv-virtualenv and `pyenv-2.7.10` in the error is the name of the environment.

```
Error: pyenv: flake8: command not found

The `flake8' command exists in these Python versions: 2.7.10/envs/pyenv-2.7.10 pyenv-2.7.10
Error: pyenv: flake8: command not found
The `flake8' command exists in these Python versions:
  2.7.10/envs/pyenv-2.7.10
  pyenv-2.7.10
    at parameters.exit (/Users/oonokenta/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.js:75:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by Arcanemagus** [comment]
Did you launch Atom from within that `virtualenv`?

**Comment by delta2323** [comment]
I tried the following ways and got the same errors whether I activate/deactivate `pyenv-2.7.10`.

* Launch `atom.app` and create new or existing python file.
* Launch from terminal by `atom foo.py`.

Is my answer to the point?

**Comment by Arcanemagus** [comment]
Just to make sure you are launching Atom from the proper environment, follow these steps:
1. Close _all_ instances of Atom
2. Open a terminal
3. Activate any necessary virtualenv
4. Verify that `flake8` works from this terminal
5. Launch Atom from this location with `atom .`

**Comment by delta2323** [comment]
I followed your instruction and the error disappears. Thank you very much. Should I close the issue by myself?

**Comment by Arcanemagus** [comment]
Glad to hear that fixes it for you, I wish there was a simpler way but unfortunately it's either launch Atom from within the virtualenv (thus inheriting its hacks to the environment), or re-write all of virtualenv's functionality in Atom to emulate it....

**Comment by glasswalk3r** [comment]
A bit late to provide some help other that find themselves in the same situation, but if you're using [pyenv](https://github.com/pyenv/pyenv-installer), don't bother trying to configure the path of the plugin or even opening Atom from inside the project, just install flake8 in the "global" python that you will use in the same virtualenv and it will work just fine.
Just don't ask me why... never got the "shim" clearly.
