### ISSUE TITLE
Flake8 is not intalling properly on 1.3.0

### ISSUE THREAD

**Issue by thevaliantx** [AtomLinter/linter-flake8#138]
Running Ubuntu 15.04 ... I do not know how to get Flake8 running with 1.30 

When I tried "apm install flake8" it said there was not version available that was compatible with 1.3,0, yet in the settings file there is an option to install it.  Installing it and restarting Atom just results in Flake8 errors suggesting that the path isn't correct or something along those line.  Otherwise, beautiful editor :)

**Comment by Arcanemagus** [comment]
`linter-flake8` (this package) is an Atom package that provides a wrapper around `flake8` so its messages can be accessed via [linter](https://github.com/atom-community/linter/). `flake8` itself is something you need to install on your system.

Have you looked over the [Installation](https://github.com/AtomLinter/linter-flake8#installation) section of the readme?

**Comment by Arcanemagus** [comment]
No response in a month and a half, closing.

**Comment by thevaliantx** [comment]
That long delay in responding might because I typically don't hang onto
programs that crash, and I'm not a developer.  I just saw your message
yesterday.
