### ISSUE TITLE
Can't see unused import

### ISSUE THREAD

**Issue by keul** [AtomLinter/linter-flake8#140]
When manually running the `flake8` script used by the plugin I also see unused import reporting, but that information seems not used by the plugin: on Atom I don't see this information.

Is this an issue or a missing feature?

**Comment by Arcanemagus** [comment]
Can you open up developer tools and put a breakpoint [here](https://github.com/AtomLinter/linter-flake8/blob/v1.9.3/lib/main.coffee#L172) and verify that the output we are getting back from `flake8` has that message in it? It's possible that is coming from a plugin for `flake8` that for some reason isn't getting loaded when Atom calls it.

**Comment by keul** [comment]
After setting the breakpoint and asking for `results` inside the console I get:

    "stdin:13:1: W293 blank line contains whitespace"

...which is a test issue I manually added. But in the same file I also added an "import urllib" that I'm not using at all.

Manually running flake8 (the same executable I put in the configuration) I get:

    .../myfile.py:7:1: F401 'urllib' imported but unused
    .../myfile.py:17:1: W293 blank line contains whitespace

**Comment by Arcanemagus** [comment]
If you close _all_ instances of Atom and then launch it from a terminal window that you see the import error in (using `atom .`), does the error show in Atom?

Currently the `flake8` process doesn't have that error in its output, so Atom can't display it. Hopefully the above will run the same `flake8`, unless you have hardcoded in the path to `flake8` in the settings?

**Comment by keul** [comment]
Mmhhh... nothing changed. I didn't see any unused import notification on Atom running it from `atom .`

Yes, the flake8 is defined in the settings.
![schermata 2016-01-18 alle 23 02 26](https://cloud.githubusercontent.com/assets/284924/12403900/94908a3c-be37-11e5-9c74-68bfa8e1ad13.png)

**Comment by Arcanemagus** [comment]
Ah, so it's not using the `flake8` from your environment. You should be able to just have that unset (and thus use the default of just `flake8`, which should resolve properly even within a virtualenv if Atom was launched from in there).

So, what you can try is:

* Set the path to nothing (default) and see if it works
* If not does `/usr/local/bin/flake8 /path/to/foo.py` show the import error in the terminal?

**Comment by can-z** [comment]
I have a similar issue where the line with the unused import error is always the last line of the file:

<img width="418" alt="screen shot 2016-02-06 at 11 32 57 pm" src="https://cloud.githubusercontent.com/assets/477525/12870911/0496ef0a-cd2a-11e5-9466-365645628dbc.png">

**Comment by hvdklauw** [comment]
@can-z That was fixed by #148 which has been released as version 1.10.1.

**Comment by Arcanemagus** [comment]
Marking this as closed due to no response from @keul. If you are still having issues feel free to comment further on here or file a new issue.
