### ISSUE TITLE
Flake8 executable path can't be a complex command

### ISSUE THREAD

**Issue by neumond** [AtomLinter/linter-flake8#141]
Often people have multiple implementations of python on the system. Running simply flake8 chooses default implementation, which in my case is 3.4. I want to use 3.5, gentoo uses handy wrappers to support multiple implementations: you can just run ```/usr/bin/flake8``` or choose different implementation by running ```python3.5 /usr/bin/flake8```. Similarly someone can run scripts like ```python3.5 -m flake8```. If I write this in settings, error occurs, telling me there is no such executable installed.

My current workaround is making separate shell file:
```
python3.5 /usr/bin/flake8 $@
```

About gentoo wrapper: https://wiki.gentoo.org/wiki/Project:Python/python-exec

**Comment by Arcanemagus** [comment]
We attempt to execute what is placed in that setting as a file in itself, you've already detailed to correct way to fix this (wrapper script) so I'm marking this as closed.
