### ISSUE TITLE
venv flake8 not from command line

### ISSUE THREAD

**Issue by JamesStidard** [AtomLinter/linter-flake8#161]
Hi,

My venv's are always in the same relative location to my projects. I was wondering if it's possible to set the executable path to a relative path instead of needing to launch atom via the terminal - like suggested in the readme.

I've tried variations of `$PATH/venv/bin/flake8` and `./venv/bin/flake8`.

Thanks.

**Comment by Arcanemagus** [comment]
This is being implemented in #143.

**Comment by JamesStidard** [comment]
Oh perfect. Thank you for the quick reply and the project in general

**Comment by Arcanemagus** [comment]
Published that in v1.12.0, not sure how I missed that that was ready earlier.
