### ISSUE TITLE
Builtins support?

### ISSUE THREAD

**Issue by franksl** [AtomLinter/linter-flake8#163]
Hello,
Is there a way to specify builtins? I'm using python gettext module and I get a lot of "F821 - undefined name '_'" because the function _ is not specified in my module.
I tried with a dummy definition of the variable _ but it breaks gettext.
Thanks,
Franco

**Comment by Arcanemagus** [comment]
Does `flake8` from the command line show the same problem? This sounds like a configuration issue that isn't related to this package.

**Comment by franksl** [comment]
Yes, flake8 from command line shows the same problem, but if I add this option:
--builtins=_

I was wondering if there's a way to pass this option through an option parameter

**Comment by Arcanemagus** [comment]
Ah! It doesn't look like there currently is.

**Comment by quamenzullo** [comment]
Same problem here. If anyone's looking for a workaround, it's possible to put a `builtins = _` line in the Project config file (take care using this removes all other settings).
