### ISSUE TITLE
Error: Unable to determine environment

### ISSUE THREAD

**Issue by silentsokolov** [AtomLinter/linter-flake8#164]
After update to v1.12.1.

First open *.py file:

```
Error: Unable to determine environment
    at /Users/***/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/consistent-env/lib/helpers.js:75:11
```
[Settings](http://i.imgur.com/LAnMYEC.jpg)

Packages:
atom-beautify@0.28.24
autocomplete-python@1.7.0
file-icons@1.6.17
git-plus@5.13.0
language-gettext@0.6.1
linter@1.11.3
linter-flake8@1.12.1
merge-conflicts@1.3.7
project-manager@2.7.6
toggle-quotes@1.0.0

**Comment by Arcanemagus** [comment]
@steelbrain Looks like a consistent-env issue.

**Comment by steelbrain** [comment]
Can you please post the value of `process.env.SHELL` from the dev tools?
Also can you do `ls -lah $SHELL` from the terminal and post the output?

**Comment by silentsokolov** [comment]
1) `process.env.SHELL`

```
> process.env.SHELL
<- "/bin/zsh"
```

2) `ls -lah $SHELL`

`-rwxr-xr-x  1 root  wheel   560K  3 дек 09:36 /bin/zsh`

**Comment by steelbrain** [comment]
That's strange, 'cause I'm on latest Mac and ZSH myself.

Can you please execute this in the shell and show us what you get
```js
var cp = require('child_process')
console.log(cp.spawnSync(process.env.SHELL, ['-c', 'source ~/.zshrc;env;exit']).stdout.toString())
```

**Comment by silentsokolov** [comment]
```
__CF_USER_TEXT_ENCODING=0x1F5:0x7:0x31
TMPDIR=/var/folders/_t/jz/T/
HOME=/Users/**
SHELL=/bin/zsh
SSH_AUTH_SOCK=/private/tmp/com.apple/Listeners
Apple_PubSub_Socket_Render=/private/tmp/com.apple/Render
PATH=/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
LOGNAME=**
XPC_SERVICE_NAME=0
COMMAND_MODE=unix2003
USER=**
XPC_FLAGS=0x0
GOOGLE_API_KEY=**
ATOM_HOME=/Users/**/.atom
NODE_PATH=/Applications/Atom.app/Contents/Resources/app.asar/exports
NODE_ENV=production
SHLVL=1
PWD=/
OLDPWD=/
ZSH=/Users/**/.oh-my-zsh
PAGER=less
LESS=-R
LC_CTYPE=
LSCOLORS=Gxfxcxdxbxegedabagacad
PYENV_ROOT=/usr/local/opt/pyenv
PYENV_SHELL=zsh
PYENV_VIRTUALENV_INIT=1
_=/usr/bin/env
```

I use Atom [project-manager](https://github.com/danielbrodin/atom-project-manager) (last release 29 days ago) for set difference python env, maybe problem in him? But, v1.12.0 its work fine.

**Comment by steelbrain** [comment]
Wow
Can you try this and reload atom to see if the error is fixed?

```
cd /Users/$USER/.atom/packages/linter-flake8/
npm install consistent-env@latest
```
or
```
apm uninstall linter-flake8
apm install linter-flake8
```

**Comment by silentsokolov** [comment]
nope :(

**Comment by steelbrain** [comment]
Can you please show the error you get after doing this?

```
cd ~/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules
rm -rf consistent-env
wget https://github.com/steelbrain/consistent-env/archive/steelbrain/debug.zip
unzip debug.zip
rm -f debug.zip
mv consistent-env-steelbrain-debug consistent-env
```

**Comment by silentsokolov** [comment]
```
Error: Unable to determine environment
    at /Users/***/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/consistent-env/lib/helpers.js:75:11
```

P.S. I don't know how show all error stack

**Comment by steelbrain** [comment]
@silentsokolov Are you on Atom slack?

**Comment by steelbrain** [comment]
We did a screensharing session and found out that the `zsh` of user was OSX default, which has bugs and doesn't work.

Installing it from brew fixed it
```
brew install zsh
```
