### ISSUE TITLE
Relative $PROJECT path no longer working

### ISSUE THREAD

**Issue by JamesStidard** [AtomLinter/linter-flake8#166]
Hi,

I'm using a relative $PROJECT path to point to my virtual environments flake8 which was working fine. Suddenly it has stopped working (maybe from an update?) and it's throwing 'Failed to spawn' errors.

The path it spits out looks correct to me so I'm not sure why it's breaking. '/Users/jamesstidard/Development/MyProject/Server/venv/bin/flake8'. I've also checked this directory and flake8 is present.

Please let me know if there are any more details I can give to help
Thanks,
James

**Comment by Arcanemagus** [comment]
Is there a permissions issue possibly? What is the full error you are seeing?

**Comment by JamesStidard** [comment]
I've attached a copy of the console .log.

I get a couple of red Atom error bubbles as well:
1. Failed to spawn command /Users/jamesstidard/Development/MyProject/Server/venv/bin/flake8. Make sure /Users/jamesstidard/Development/MyProject/Server/venv/bin/flake8 is installed and on your PATH

2. Error: spawn /Users/jamesstidard/Development/MyProject/Server/venv/bin/flake8 ENOENT
Error: spawn /Users/jamesstidard/Development/MyProject/Server/venv/bin/flake8 ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

P.S. I don't prefix my venv with a dot.

**Comment by Arcanemagus** [comment]
What do you get from running the following?
```shell
cd /Users/jamesstidard/Development/MyProject/Server/venv/bin
ls -l
```

The error is claiming that the file doesn't exist, but you say that it is, so _something_ funky is going on.

**Comment by JamesStidard** [comment]
Funky indeed. Here's the dump:

> total 320
drwxr-xr-x  15 jamesstidard  staff    510 27 Feb 21:09 __pycache__
-rw-r--r--   1 jamesstidard  staff   2275 27 Feb 21:09 activate
-rw-r--r--   1 jamesstidard  staff   1301 27 Feb 21:09 activate.csh
-rw-r--r--   1 jamesstidard  staff   2514 27 Feb 21:09 activate.fish
-rw-r--r--   1 jamesstidard  staff   1137 27 Feb 21:09 activate_this.py
-rwxr-xr-x   1 jamesstidard  staff    619 27 Feb 21:09 createfontdatachunk.py
-rwxr-xr-x   1 jamesstidard  staff    268 27 Feb 21:09 dotenv
-rwxr-xr-x   1 jamesstidard  staff    284 27 Feb 21:53 easy_install
-rwxr-xr-x   1 jamesstidard  staff    284 27 Feb 21:53 easy_install-3.5
-rwxr-xr-x   1 jamesstidard  staff   1569 27 Feb 21:09 enhancer.py
-rwxr-xr-x   1 jamesstidard  staff   2500 27 Feb 21:09 explode.py
-rwxr-xr-x   1 jamesstidard  staff    275 27 Feb 21:09 flake8
-rwxr-xr-x   1 jamesstidard  staff    703 27 Feb 21:09 gifmaker.py
-rwxr-xr-x   1 jamesstidard  staff   2169 27 Feb 21:09 painter.py
-rwxr-xr-x   1 jamesstidard  staff    270 27 Feb 21:09 pep257
-rwxr-xr-x   1 jamesstidard  staff    270 27 Feb 21:09 pep8
-rwxr-xr-x   1 jamesstidard  staff   2420 27 Feb 21:09 pilconvert.py
-rwxr-xr-x   1 jamesstidard  staff  15636 27 Feb 21:09 pildriver.py
-rwxr-xr-x   1 jamesstidard  staff   2728 27 Feb 21:09 pilfile.py
-rwxr-xr-x   1 jamesstidard  staff   1089 27 Feb 21:09 pilfont.py
-rwxr-xr-x   1 jamesstidard  staff   2599 27 Feb 21:09 pilprint.py
-rwxr-xr-x   1 jamesstidard  staff    267 27 Feb 21:09 pip
-rwxr-xr-x   1 jamesstidard  staff    267 27 Feb 21:09 pip3
-rwxr-xr-x   1 jamesstidard  staff    267 27 Feb 21:09 pip3.5
-rwxr-xr-x   1 jamesstidard  staff   2235 27 Feb 21:09 player.py
-rwxr-xr-x   1 jamesstidard  staff    276 27 Feb 21:09 pyflakes
lrwxr-xr-x   1 jamesstidard  staff      9 27 Feb 21:08 python -> python3.5
lrwxr-xr-x   1 jamesstidard  staff      9 27 Feb 21:08 python3 -> python3.5
-rwxrwxr-x   1 jamesstidard  staff  25384 27 Feb 21:08 python3.5
-rwxr-xr-x   1 jamesstidard  staff   1856 27 Feb 21:09 thresholder.py
-rwxr-xr-x   1 jamesstidard  staff   1029 27 Feb 21:09 viewer.py
-rwxr-xr-x   1 jamesstidard  staff    263 27 Feb 21:53 wheel

**Comment by JamesStidard** [comment]
It looks like a conflict with the MagicPython package. When I disable MagicPython I no longer get the errors.

**Comment by Arcanemagus** [comment]
What in the world...? `language-python` for sure shouldn't be affecting this (other than marking files as Python).

**Comment by JamesStidard** [comment]
Just updated to 1.13.0 and the errors are gone. Don't know if they have just been silenced or it's working now.

**Comment by Arcanemagus** [comment]
v1.13.0 does silence a potential error, but not one that would be related to this. In any case I'm willing to chalk it up to gremlins and close this if you aren't seeing this any more.

**Comment by JamesStidard** [comment]
Sorry false report. I wrote $PROJECTS instead of $PROJECT so it was using my fallback python instead

**Comment by JamesStidard** [comment]
Solved. I had moved my virtual environment so it's $VIRTUAL_ENV was still pointing to it's old location. I don't know if that's in scope of your project to handle.

Thanks for being my rubber duck and your quick responses. You can have your weekend back now :)

**Comment by Arcanemagus** [comment]
Glad you got it figured out :wink:
