### ISSUE TITLE
Unable to determine environment

### ISSUE THREAD

**Issue by jjlorenzo** [AtomLinter/linter-flake8#168]
```
Error: Unable to determine environment
    at /Users/jjlorenzo/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/consistent-env/lib/helpers.js:75:11
```

What it is open it is a rails project, so, in the first place, why this linter is activated.

Version `1.13.0`

**Comment by Arcanemagus** [comment]
I'm guessing that you have a different linter (that is actually associated with the Rails file you had open) installed as well as `linter-flake8`. As most of the linters utilize the same helper library, Atom will often load the first instance and use that for all linters. In this case it looks like it simply chose the one installed in `linter-flake8`'s folder.

As to why you were seeing this I'm not entirely sure. What OS are you on?

**Comment by jjlorenzo** [comment]
OSX 10.11.3.
I reinstall the linter-flake8 (uninstall then install), restart Atom and it
seems fixed now.

Probably was an update problem.
​

**Comment by Arcanemagus** [comment]
Interesting, closing this in that case.

If you run into any other issues feel free to report them :wink:.
