### ISSUE TITLE
Missing docstring in public module error D100

### ISSUE THREAD

**Issue by epicallan** [AtomLinter/linter-flake8#170]
I keep getting this error despite having added a module doc string. I have flake8 docstrings 0.2.5 installed

**Comment by Arcanemagus** [comment]
Have you tried `flake8-pep257` one of them has an issue with `stdin` input, and from your issue I'm guessing it's `flake8-docstrings`.

**Comment by epicallan** [comment]
yes thats is what is installed, so should I downgrade or upgrade to another version??

**Comment by Arcanemagus** [comment]
Those are two different packages, which do you have installed?

**Comment by epicallan** [comment]
I have flake8 , flake8-docstrings and hacking installed via pip

**Comment by Arcanemagus** [comment]
Do you still see this if you run the following?

```ShellSession
pip uninstall flake8-docstrings
pip install flake8-pep257
```

**Comment by epicallan** [comment]
yes still get the error after running the above.

**Comment by nikaro** [comment]
Since yesterday i got this error too. I think that flake8 received an update recently, may be it comes from there.

```
flake8==3.0.2
flake8-docstrings==1.0.2
```

PS: flake8-pep257 seems obsolete.

**Comment by Arcanemagus** [comment]
Do you see the same when you do `cat foo.py | flake8 -`?

**Comment by nikaro** [comment]
Yes i see the same with this command. It's strange that with `flake8 foo.py` it outputs nothing… :-/

So it's a bug in flake8[-docstrings] ?

**Comment by Arcanemagus** [comment]
Most likely it's the same bug that just has never been fixed.

From what I understand processing `stdin` input follows a completely different path, and breaks somewhat easily with plugins to `flake8`.

**Comment by Arcanemagus** [comment]
Marking this as closed, it's an external issue that we have no control over here.

**Comment by mlalkaka** [comment]
For reference, this is the external bug logged to fix this issue in the flake8-docstrings repository: [Issue #13: D100 is triggered when reading from stdin](https://gitlab.com/pycqa/flake8-docstrings/issues/13).

**Comment by jay0lu** [comment]
To fixed the warning, I installed flake8-pep257.
`pip install flake8-pep257`

**Comment by mlalkaka** [comment]
I tried running `pip install flake8-pep257`, but that didn't help. It looks like flake8-pep257 and pep257 have been renamed to flake8-docstrings and pydocstyle, respectively. So I don't think there should be a need for flake8-pep257 anymore anyway.

**Comment by Arcanemagus** [comment]
@mlalkaka `flake8-docstrings` is a different module from `flake8-pep257`, not a rename.

**Comment by mlalkaka** [comment]
Oh, sorry about that, I was incorrect. It looks like only pep257 was renamed to pydocstyle. The packages flake8-docstrings and flake8-pep257 are independent, but there haven't been updates to flake8-pep257 in a while.

**Comment by Arcanemagus** [comment]
Yea, and unfortunately both have had alternating issues with working properly, and at the moment I'm not sure which, if _either_, actually works.
