### ISSUE TITLE
Error installing linter-flake 8

### ISSUE THREAD

**Issue by kantawan** [AtomLinter/linter-flake8#171]
I tried to install linter-flake 8 using https://atom.io/packages/linter-flake8

and when I opened Atom, I got an error that says

> Failed to spawn command /usr/local/bin/flake8. Make sure /usr/local/bin/flake8 is installed and on your PATH

and

> Error: spawn /usr/local/bin/flake8 ENOENT

I have when I installed linter-flake 8 I typed these to my terminal ( I have OS x El Capitan 10.11.2)

```
$pip install flake8
```
```
$apm install linter-flake8
```
```
$pip install flake8-docstrings
```
```
$pip install hacking
```
```
$pip install flake8
```
and the error still shows up? Is there anything I can do here?

**Comment by Arcanemagus** [comment]
What do you get when you run `which flake8` in a terminal?

**Comment by kantawan** [comment]
@Arcanemagus I get nothing

**Comment by Arcanemagus** [comment]
Something is wrong with your Python installation then, since wherever `pip` is installing things isn't in your PATH.

You could hunt that down and manually put the path in your `linter-flake8` settings (which it looks like you might have tried to do already?), but it's probably a better idea to figure out why it isn't in your PATH.

**Comment by jbkalmbach** [comment]
Hi, I am having this same problem. However, flake8 is definitely on my PATH. From command line <code>which flake8</code> gives me <code>/Users/..../anaconda/bin/flake8</code>.

**Comment by jbkalmbach** [comment]
Took your advice above and manually added the above location to my <code>linter-flake8</code> settings and it worked.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response from @kantawan, if you are still experiencing this issue feel free to repoen this or file a new issue!

**Comment by ashleylk** [comment]
I think I'm having a similar problem installing linter-flake8.  flake8 works in the command prompt but I get errors in atom.  I pip installed flake8, flake8-docstrings, and apm installed linter and linter-flake8.

I was getting the same 'failed to spawn command' error as above and so added my flake.exe path to the linter-flake8 settings.  I adjusted the executable path in the linter-flake8 settings to C:/Users/ ... /Python37-32/Scripts/flake8, but now I get this error anytime I type into a new file in atom:

![flake8error](https://user-images.githubusercontent.com/35382143/34894515-c4118cd0-f7af-11e7-8eed-582d1d8036ab.JPG)


(Using Windows 10)

**Comment by Arcanemagus** [comment]
@ashleylk That error is coming from `flake8`, you'll need to figure out why it is returning that.

Locking this issue as the original filer hasn't responded and the other posts in here should be new issues anyway.
