### ISSUE TITLE
flake8 unaware of the filename of the scanned file

### ISSUE THREAD

**Issue by leorochael** [AtomLinter/linter-flake8#174]
currently, `linter-flake8` lints the file by piping the file content to `flake8` stdin, with a command line like:

```
flake8 --max-complexity -1 --config /path/to/you/project/.flake8 -
```

(depending on your configuration, i.e. if it has `.flake8` set as `Project Config File`).

However, this means that rules about file names stored int the configuration file are not taken into account (i.e., settings like `exclude` and `filename`).

In my particular case, I'm using [flake8-putty](https://github.com/jayvdb/flake8-putty) and the stdin-feeding is causing the `putty-ignore` rules with file patterns to be skipped.

I understand that `stdin` is used because we want to lint the unsaved contents of the file, and unfortunately I haven't found any `flake8` switch for specifying what is the name of the file piped in the stdin, so this issue might not be able to be solved in the general case.

But if the file is saved, flake8 should be invoked on the actual file in the filesystem to avoid this issue.

**Comment by Arcanemagus** [comment]
Just filed https://gitlab.com/pycqa/flake8/issues/129, we'll see what they say about getting this fixed in the source before we attempt to work around it here.

**Comment by leorochael** [comment]
The definitive fix for this issue should be lower on the stack, actually. on `pep8`. [Check this PR](https://github.com/PyCQA/pycodestyle/pull/493).

**Comment by Arcanemagus** [comment]
I wouldn't be that against adding a check to `editor.isModified()` and changing how `flake8` is called if you want to put that together, as I see it right now though that's added complexity for an upstream bug.
