### ISSUE TITLE
No unused imports (and other) issues with non-default flake8 executable path

### ISSUE THREAD

**Issue by V0idExp** [AtomLinter/linter-flake8#195]
In my project (with virtualenv) I have a `flake8` binary installed with `pip`, to which I'm pointing the `linter-flake8` package by providing the path in settings as `$PROJECT/bin/flake8;/usr/local/bin/flake8`. I also tried leaving the default `flake8` value there and invoking Atom with `PATH=/path/to/project/bin:$PATH atom`, but the results are the same: unused imports and other issues are ignored and the linter reports `No issues`.
The `flake8` executable is invoked for sure, because if I try to type `import` statement without the required module name, it reports a syntax error, I'm just wondering why it ignores other errors.
Executing the very same `flake8` binary on my source files from command line, reports all the errors I expect to see.
The only difference is that the project is using Python 3.5, while system-wide installed Python is 2.7, that's the reason I'm trying to use custom `flake8` binary: the one installed in my project's virtualenv is for Python3.

**Comment by V0idExp** [comment]
With default Python2 `flake8` binary in `/usr/local/bin/flake`:
![screenshot from 2016-05-12 12 56 54](https://cloud.githubusercontent.com/assets/595098/15212472/21472f40-1841-11e6-9fa9-e89fb0c52228.png)

With custom Python3 `flake8` binary in my project's virtualenv:
![screenshot from 2016-05-12 12 57 16](https://cloud.githubusercontent.com/assets/595098/15212488/3a9a7a56-1841-11e6-9eef-f3008a884047.png)
![screenshot from 2016-05-12 12 57 31](https://cloud.githubusercontent.com/assets/595098/15212491/3dc1188e-1841-11e6-8ca9-ed9e8ef8942c.png)

**Comment by Arcanemagus** [comment]
Hmmm, is the unused import checking coming from a `flake8` plugin? We are sending the contents of the file to `flake8` over `stdin`, which _many_ `flake8` plugins have issues with.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If you are still experiencing problems feel free to re-open with more information.
