### ISSUE TITLE
How to disable a specific warning check.

### ISSUE THREAD

**Issue by Pradeet** [AtomLinter/linter-flake8#198]
When i am using flake it is giving me a warning on every line saying "W191 - Indentation contains tabs".
So how do i disable this check.

![image](https://cloud.githubusercontent.com/assets/8604754/15644911/47007828-2673-11e6-989d-5ebfa4121773.png)

**Comment by Arcanemagus** [comment]
Simply add `W191` to the list of Ignored Error Codes in the settings.
