### ISSUE TITLE
E501 error when line contains Unicode characters

### ISSUE THREAD

**Issue by poofeg** [AtomLinter/linter-flake8#200]
E501 error when line contains Unicode characters on:
Atom 1.7.4
linter-flake8 1.13.0
Windows 10 64-bit
Python 3 (3.5.1)
flake8 2.5.4
line: """АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвг."""
error: E501 — line too long (80 > 79 characters)
![2016-06-06_22-53-01](https://cloud.githubusercontent.com/assets/586294/15831977/973963f6-2c39-11e6-95af-e8bd4e1dad2f.png)

Checking the same file with flake8 utility does not find errors.
Same file on Linux host behaves as expected.

**Comment by Arcanemagus** [comment]
Hmmm, that error is coming from `flake8` though... can you put a breakpoint [here](https://github.com/AtomLinter/linter-flake8/blob/v1.13.0/lib/main.coffee#L206) and see what `parameters` contains?

**Comment by poofeg** [comment]
parameters: Array[3]
0: "--max-complexity"
1: -1
2: "-"
length: 3

**Comment by poofeg** [comment]
I have found that:
<pre>>flake8 --max-complexity -1 - < etetetetet.py
stdin:2:80: E501 line too long (80 > 79 characters)

>flake8 --max-complexity -1 etetetetet.py

></pre>

**Comment by Arcanemagus** [comment]
Ah, so it's `flake8` having issues with `stdin`.

You should file an issue [over here](https://gitlab.com/pycqa/flake8/issues) so they can look into it.

**Comment by poofeg** [comment]
No, I think it is pep8.
<pre>>pep8 - < etetetetet.py
stdin:2:80: E501 line too long (80 > 79 characters)</pre>
