### ISSUE TITLE
Error: spawn flake8 ENOENT

### ISSUE THREAD

**Issue by edwinksl** [AtomLinter/linter-flake8#202]
I am using Atom on the Beta channel on a Ubuntu 16.04 machine:

    $ uname -a
    Linux e6320 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

    $ atom-beta -v
    Atom    : 1.9.0-beta0
    Electron: 0.37.8
    Chrome  : 49.0.2623.75
    Node    : 5.10.0

I have a virtualenv in which I use `pip` to install `flake8`. If I open Atom using the Unity Launcher, Atom gives an error message that says:

    Error: spawn flake8 ENOENT
        at exports._errnoException (util.js:890:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
        at onErrorNT (internal/child_process.js:348:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)

On the other hand, if I open Atom from the terminal by running `atom-beta`, Atom does not give the error message above and `linter-flake8` works as expected. It may be useful to note that other linters that I have such as `linter-markdown` works as expected regardless of whether I open Atom from the Unity Launcher or the terminal, so I think the error message is caused by `linter-flake8` rather than the base `linter` package.

**Comment by Arcanemagus** [comment]
The error message is actually caused by `virtualenv` and Unity 😛.

Unity has no idea what your environment in the terminal is right then, so it uses a default one. Depending on how your `virtualenv` is set up you probably just need to set a path to `flake8` based on the project path in your `linter-flake8` settings.

**Comment by edwinksl** [comment]
@Arcanemagus Ah, you are probably right. :smile: 

The `README.md` says "Then activate your virtualenv from the command line before starting Atom, and you're good to go!", which gives me the impression `linter-flake8` would work regardless of whether I can start Atom from Unity or the command line.

**Comment by Arcanemagus** [comment]
That was probably written with the assumption of running Atom with `atom .` from within the terminal.
