### ISSUE TITLE
flake8 returning oddly encoded data

### ISSUE THREAD

**Issue by Jyree** [AtomLinter/linter-flake8#204]
Hi, i installed this plugin and it doesn't work . 
![image](https://cloud.githubusercontent.com/assets/8149366/16021635/6f78bd48-31bc-11e6-9f3e-eb765d00a0ea.png)
As you can see, 0 issues found, but...
![image](https://cloud.githubusercontent.com/assets/8149366/16021659/9149f7d4-31bc-11e6-802b-639dc06e60ee.png)

**Comment by Arcanemagus** [comment]
Can you open Atom's Developer Tools, place a breakpoint [here](https://github.com/AtomLinter/linter-flake8/blob/v1.13.1/lib/main.coffee#L228) and report back with what `result` contains?

**Comment by Jyree** [comment]
@Arcanemagus when i'm trying to place a breakpoint it jumps to another line
![image](https://cloud.githubusercontent.com/assets/8149366/16022013/718a6f26-31be-11e6-894c-ad150f12eb77.png)
also in "Watch" bar it seems unavailable

**Comment by Jyree** [comment]
oh, i did it 
![image](https://cloud.githubusercontent.com/assets/8149366/16022108/e82090ac-31be-11e6-8423-760dcd3c2aec.png)
but there are encoding troubles it seems

**Comment by Jyree** [comment]
couldn't decode it, sorry(

**Comment by Arcanemagus** [comment]
Wow, that's a new one 😮.

What shell are you using in the screenshot above where you are running `flake8`? Does it work from the "Command Prompt" shell?

**Comment by Jyree** [comment]
Standard Windows 10 shell

**Comment by Jyree** [comment]
@Arcanemagus
Standard Windows 10 shell
Yeas, it works

**Comment by Jyree** [comment]
I've updated it few mins ago
![image](https://cloud.githubusercontent.com/assets/8149366/16045631/f67e3486-3251-11e6-9f67-21e7ac4b67de.png)
but still having the same output
![image](https://cloud.githubusercontent.com/assets/8149366/16045666/1dc98f22-3252-11e6-8459-a80c91c27bda.png)

**Comment by Arcanemagus** [comment]
What language is Windows set to?

**Comment by Jyree** [comment]
Russian

**Comment by Jyree** [comment]
Can I somehow set the encoding for this string to utf-8 to make it readable?

**Comment by Arcanemagus** [comment]
Hmm, I'm betting that that is the "flake8 can't be found" message, can you try putting the output of `where.exe flake8` in the Executable Path setting?

**Comment by Jyree** [comment]
Yeah, now it works!)
Thanks again!

**Comment by Arcanemagus** [comment]
Awesome, glad that was it!
