### ISSUE TITLE
Tried to Update to 1.13.2 - Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by niklasben** [AtomLinter/linter-flake8#206]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Linux Mint
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:29.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-atom-dark-syntax.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "openEmptyEditorOnStart": false,
    "projectHome": "/media/niklas/Shared/GitHub/",
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.2.13
autocomplete-python, v1.8.1
file-type-icons, v1.3.0
javascript-snippets, v1.2.1
linter, v1.11.10
linter-flake8, v1.13.0
minimap, v4.24.6
pigments, v0.29.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Your Atom is out of date... and nothing in that stack trace has to do with this package so I'm a bit confused as to why it was filed here?

**Comment by niklasben** [comment]
I am just realising I have 1.8.0 (https://github.com/atom/atom/releases), which is the most recent version I can get from the ppa for the 32Bit System and I just posted it, because that's the error I got while trying to update the package and I assumed that this is relevant for this.

**Comment by Arcanemagus** [comment]
Your error that you posted claims you are running Atom v1.7.3, not v1.8.0, so something didn't work correctly in your update.

Sometimes Atom does odd things when updating packages, if the package isn't working properly re-install it, otherwise I would just ignore it. Again though, the error posted above has nothing to do with this package.
