### ISSUE TITLE
Stops working after upgrading flake8 from 2.5.5 to 2.6.0

### ISSUE THREAD

**Issue by edwinksl** [AtomLinter/linter-flake8#208]
`linter-flake8` has stopped working after I upgraded `flake8` from 2.5.5 to 2.6.0 using `pip`. I am not sure if this is a bug with `linter-flake8` or `flake8` though. If it is the latter, please let me know so that I can file a bug report with `flake8` instead.

**Comment by Arcanemagus** [comment]
I'm betting the output format changed with this version, breaking the regex. Looking into it.

**Comment by Arcanemagus** [comment]
Hmmm, this actually works perfectly fine for me on the following versions:
```
2.6.0 (pycodestyle: 2.0.0, pyflakes: 1.2.3, flake8_coding: 1.2.1, flake8-docstrings: 0.2.7, pep257: 0.7.0, mccabe: 0.5.0) CPython 2.7.11 on Windows
```

Are you able to share the file this isn't working on?

**Comment by edwinksl** [comment]
Yup, I should have provided a minimal working example earlier.

Given the following code

```python
def a():
    print('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')


def b:
    print('b')
```

`linter-flake8` gives 3 errors as expected:

```
Error E501 — line too long (88 > 79 characters) at line 2 col 80
Error E901 — SyntaxError: invalid syntax at line 5 col 7
```

Now, let's comment out the definition of `b`. Given the following code

```python
def a():
    print('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')


# def b:
#     print('b')
```
`linter-flake8` gives 0 errors when it should have given a E501 error.

**Comment by Arcanemagus** [comment]
Hmm, still not able to reproduce:
![image](https://cloud.githubusercontent.com/assets/427137/16136496/dfd5c5e8-33df-11e6-8269-f8b6f7787044.png)

**Comment by edwinksl** [comment]
`flake8 --version` gives `2.6.0 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.0, flake8-docstrings: 0.2.7, pep257: 0.7.0, hacking.core: 0.0.1, ProxyChecker: 0.0.1) CPython 3.5.1+ on Linux`.

Without commenting out the definition for `b`, `flake8 foo.py` gives:
```
foo.py:2:80: E501 line too long (88 > 79 characters)
foo.py:5:7: E901 SyntaxError: invalid syntax
```
Commenting out, `flake8 foo.py` gives:
```
foo.py:1:1: D100 Missing docstring in public module
foo.py:1:1: D103 Missing docstring in public function
foo.py:2:80: E501 line too long (88 > 79 characters)
```

I also did the same test with Python 2.7.11. Running the same code without commenting out the definition for `b` gives
```
Error E501 — line too long (88 > 79 characters) at line 2 col 80
Error E901 — SyntaxError: invalid syntax at line 5 col 7
```
while commenting it out gives
```
Error E501 — line too long (88 > 79 characters) at line 2 col 80
Warning D100 — Missing docstring in public module at line 1 col 1
```
It seems the `D100` warning should also have appeared when the definition of `b` is not commented out but intriguingly, it only appears after the definition of `b` is commented out.

**Comment by edwinksl** [comment]
It looks like this has been fixed after the latest update to `linter` to `1.11.14`. Please feel free to close this issue, thanks!
