### ISSUE TITLE
show messages farther from the current line

### ISSUE THREAD

**Issue by johnyf** [AtomLinter/linter-flake8#222]
The `flake8` message is shown below the line where the text cursor is. This occludes the next line, which usually is very relevant to the current line that is being edited. It would be convenient to show the message a few lines below or above the current line. Perhaps how fat away one prefers it could be made available as a configuration parameter.

I am not sure whether there already exists some way to configure this.

**Comment by Arcanemagus** [comment]
I'm not entirely sure what you are asking here, but in any case this package has nothing to do with the UI.  You should ask this over on [linter](https://github.com/steelbrain/linter) as it provides the UI you see.
