### ISSUE TITLE
format=pylint directive in setup.cfg will cause linter-flake8 to stop working.

### ISSUE THREAD

**Issue by ghurley** [AtomLinter/linter-flake8#225]
If there is a setup.cfg file in the project directory and it contains a `[flake8]` section that includes the following directive:

`format=pylint`

then the linter will not run. There are no errors in the developer console.

Arguably, this isn't a bug since presumably the linter is made to deal with output from flake8 and here we're telling flake8 to output in a different format. It's exceptionally annoying for me however because I'm working on a project that has such a setup.cfg file which I can't change (it's there for some downstream Jenkins tests) and so I can't actually get any flake8 lint errors from within Atom.

I would probably be fine with being able to overrride the project's setup.cfg file with one in my home directory but that doesn't seem to be supported.

**Comment by Arcanemagus** [comment]
Fixed in #217 (it just wasn't released yet).
