### ISSUE TITLE
pep8 project configuration file properties are ignored in some cases

### ISSUE THREAD

**Issue by badray** [AtomLinter/linter-flake8#23]
When user will try to use project config (implemented in https://github.com/AtomLinter/linter-flake8/pull/17), for example a config which have a `maxLineLenght` property, `flake8` will ignore config value, and will use value from plugin settings.

This behaviour is bad when user has not set any parameters in `linter-flake8` settings by himself and want to use only the config file, `pep8` will take a higher priority for arguments and values in config file will be ignored.

Any proposals how to handle this? I think you guys can help me becouse you've were somehow involved in this issue :) @ChaoticMind @matthewwithanm  

My proposals:
1. If property from plugin settings (ex. `maxLineLength`) have the default value(ex. `79`) and config file is found, don't use default values, but use value if it is `property!= default` value.
2.  Totaly ignore plugin settings if config file is found.

This is the last thing that stopped me from making new release.

**Comment by knyghty** [comment]
Option 2 makes the most sense to me. If I'm using a config file, I want it to use the config file, not (what I would consider defaults) in the plugin settings. I can't think of a single reason I'd want to override my config settings, instead of just temporarily changing the config file itself.

**Comment by matthewwithanm** [comment]
Yeah, I prefer option two too. Honestly, I think it would be best to not have any linter config in the plugin settings and just encourage people to configure linting using the normal means (setup.cfg, tox.ini, etc).

**Comment by badray** [comment]
@knyghty @matthewwithanm Thanks! You've just stimulated my brain and I've got idea that will cover this two options: The checkbox with option to **ignore plugin settings when config found**, defaultly set to true?

**Comment by matthewwithanm** [comment]
That works, though I can't think of a time when you'd have a config file but *not* want to ignore plugin settings.

**Comment by badray** [comment]
Option `2` choosed.

**Comment by matthewwithanm** [comment]
:thumbsup: Great, thanks!
