### ISSUE TITLE
linter-flake8 is not working, no error messages

### ISSUE THREAD

**Issue by geokis** [AtomLinter/linter-flake8#236]
Sorry guys  for the stupid issue, but I spend a few hours to find a solution through the web and unfortunately nothing works :(

I am not a programmer and usually I use Pythons IDLE.
So I installed **Atom 1.9.8** on **Windows7 x64** as normal user. (update to Atom **1.9.9**) 

> Python Path: **C:\Program Files\Python35**

I set Python as system variable and installed:
```
pip install pep8
pip install flake8
pip install flake8-docstrings
pip install hacking
```
>flake8 Path: **C:\Program Files\Python35\Lib\site-packages\flake8**

Launched Atom as nornal user and installed the following packages:

- linter
- linter-flake8
- python-autopep8
- autocomplete-python
- script

For **script** I installed **git** for Windows.

I entered in the flake8 packages settings the flake8 path as _**executable path**_
Restart Atom, no error messages appear,  typing some lines and nothing... no linter messages :(

I tried to set the path in the **init.coffee** file
```
`process.env.PATH = ['C:\\Program Files\\Python35\\Lib\\site-packages\\flake8', process.env.PATH].join(':')
```
but it is still not working.

What is going wrong?

**Comment by Arcanemagus** [comment]
First of all you shouldn't need that PATH modification in your init.coffee.

What happens if you put the output of `where.exe flake8` in the executable path setting? (Most likely this will be `C:\Program Files\Python35\Scripts\flake8.exe`)

**Comment by geokis** [comment]
@Arcanemagus 
Oh man, **really big thanks** :+1: 
It is working :tada: 

At the beginning of my journey  I set the path to `C:\Program Files\Python35\Scripts\` 
Because in the documentation the path is always set to the folder and not to the `.exe`-file I have not tried it.

**Thanks again!**

**Comment by Arcanemagus** [comment]
Marking this as closed then 😉.

Btw, [the documentation](https://github.com/AtomLinter/linter-flake8#settings) shows the full path to the executable, so I'm not sure what you mean there.

**Comment by geokis** [comment]
You mean on Linux the equivalent of `...\Python35\Scripts\flake8.exe`
 is `/usr/bin/flake8` ?

My fault, I thought `flake8` is the folder...  \*_ShameOverMe_\*

**Comment by Arcanemagus** [comment]
Well, that's most likely a symlink, which makes the same file appear in more than one place on the file system, but yes 😉.
