### ISSUE TITLE
Getting the same error.

### ISSUE THREAD

**Issue by PaddoInWonderland** [AtomLinter/linter-flake8#267]
On each keystroke I get the same error.

![image](https://cloud.githubusercontent.com/assets/18600886/19719790/c8941b66-9b6b-11e6-80db-14e1cf5c40e6.png)

**Comment by Arcanemagus** [comment]
@PaddoInWonderland do you have `flake8` installed and available in your `%PATH%`? Running `where.exe flake8` should return a path like `C:\Python27\Scripts\flake8.exe`.

**Comment by richardhenry** [comment]
oops, didn't mean to reference this issue

**Comment by PaddoInWonderland** [comment]
@Arcanemagus I have reinstalled flake8 and that seems to have solved the issue.

**Comment by Arcanemagus** [comment]
Marking this as closed based on the above.
