### ISSUE TITLE
Some Files get ignored/excluded

### ISSUE THREAD

**Issue by ChristophRob** [AtomLinter/linter-flake8#269]
I somehow excluded all my "admin.py" files from linter-flake8 2.0.2 for atom. So every file is perfectly monitored by the linter-flake8 except my admin.py files in different folders. I don't know how that happened. It's not in the .flake8 - configuration excludes

**Comment by ChristophRob** [comment]
so it works again...
reinstall linter or atom-linter plugin won't work. But reopen the project folder does fix the bug...

**Comment by Arcanemagus** [comment]
Sounds like you might have had the file excluded by your VCS, and left that functionality enabled in `linter`? In either case, I'm glad it's working for you again!
