### ISSUE TITLE
only run flake8 if flake8 is present

### ISSUE THREAD

**Issue by deanmalmgren** [AtomLinter/linter-flake8#274]
I have lots of projects on my laptop but I do not have `flake8` (nor do I want to have `flake8`) installed in the virtual environment for every one of my projects. It would be nice if `linter-flake8` respected my desire to not install `flake8` globally instead of throwing these errors that occur whenever it tries to launch `flake8`:

<img width="452" alt="screen shot 2016-11-15 at 4 05 54 am" src="https://cloud.githubusercontent.com/assets/255672/20301557/54cc7312-aae9-11e6-8f43-e16a4a580a65.png">

Is it possible to conditionally report `flake8` violations if and only if `flake8` is actually present?

It might be worthwhile to throw a one-time warning (at start-up?) that displays to show that `linter-flake8` will not work without flake8 installed.

**Comment by Arcanemagus** [comment]
Hmmm, I'm tempted to simply mark this as wontfix, but I'm open to moving this to a warning on the first time a lint is called on a file (instead of spamming you on every change to the file!).

**Comment by lydell** [comment]
I set the "Executable path" to `$PROJECT/.venv/bin/flake8;/bin/true`. `true` is a standard unix tool that does nothing and exits with a non-zero exit code. Kind of a hack and perhaps not very portable, but works for me.

**Comment by deanmalmgren** [comment]
Nice. That works for me too. I have all of my virtualenvs in my home directory, so I set the executable path to `$VIRTUAL_ENV/bin/flake8;/usr/bin/true`

**Comment by Arcanemagus** [comment]
Marking this as closed, there's a workaround posted here and nobody has found this important enough to submit a PR for it in the first place 😉.
