### ISSUE TITLE
Don't lint current line

### ISSUE THREAD

**Issue by Asday** [AtomLinter/linter-flake8#275]
It's really annoying when I stop typing for a second to think, and a big intrusive tooltip appears telling me I'm wrong about something.

Could this be changed?

![screen shot 2016-11-15 at 11 14 01](https://cloud.githubusercontent.com/assets/340276/20303795/083055f0-ab25-11e6-9b47-bd4204603dbd.png)

**Comment by Arcanemagus** [comment]
You can disable on the fly linting in `linter`, but there isn't really a way to reliably do what you are asking here.
