### ISSUE TITLE
activationHooks breaks package loading

### ISSUE THREAD

**Issue by yokujin** [AtomLinter/linter-flake8#280]
After upgrade to version 2.1.0, package stopped working. It does nothing at all. No flake8 script is run. No errors checked or displayed. It looks like it is not installed. But it exists in the list of installed packages and it is not disabled.

After short investigation I found out that removing this portion of package.json recovers package:
```json
"activationHooks": [
  "language-python:grammar-used"
],
```

Atom version: 1.12.4

**Comment by yokujin** [comment]
Possibly it is because the syntax of my .py files set to 'Python Django' instead of just 'Python'...

**Comment by hvdklauw** [comment]
I have the same issue, MagicPython/Python Django does not work, but Python does.

**Comment by Arcanemagus** [comment]
Fixed in v2.1.1, thanks again @walles!
