### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by henryrizzi** [AtomLinter/linter-flake8#284]
I know this is a duplicate issue, but I keep on running into this lately and I'm not exactly sure what to do about it.

Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: EOL while scanning string literal`.

Debug information:
Atom version: 1.12.5
Flake8 version: `3.2.0 (flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, pycodestyle: 2.2.0, pyflakes: 1.3.0, mccabe: 0.5.2) CPython 3.5.2 on Darwin`

**Comment by henryrizzi** [comment]
Oops. The line number and line position were incorrect, but the error was justified. Sorry!

**Comment by Arcanemagus** [comment]
Btw, `flake8==3.2.1` (released 2 days ago) should hopefully fix the invalid points coming from it for these `E999` errors, if you see this again after updating to that version _please_ report it and include code to reproduce the error so it can be reported and fixed in `flake8`!
