### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by patelnav** [AtomLinter/linter-flake8#285]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

File name is "helper.py", first line shows the error: 

import logging <---
from flask import Flask
....

Debug information:
Atom version: 1.12.5
Flake8 version: `2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, pep257: 0.2.1.post1, mccabe: 0.3.1) CPython 2.7.10 on Darwin`

**Comment by patelnav** [comment]
Uninstalling "linter-flake8" and re-installing it seems to fix this

**Comment by Arcanemagus** [comment]
That message actually has nothing to do with `linter-flake8`, your version of `flake8` is very out of date and it's likely you are hitting a bug fixed in v3.1.0.
