### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by kayfhan** [AtomLinter/linter-flake8#286]
Flake8 reported an invalid point for the rule `E901`, with the messge `IndentationError: expected an indented block`.

Debug information:
Atom version: 1.10.2
Flake8 version: `2.5.5 (pep8: 1.5.7, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, mccabe: 0.5.2, hacking.core: 0.0.1, ProxyChecker: 0.0.1, pyflakes: 1.3.0) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version, v3.1.0 likely fixed the bug you are running into here, while v3.2.1 fixed the entire class of `E999` related bugs.

(Note: Your version is old enough that it still calls these errors `E901` 😛)

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still experiencing this after updating to `flake8>=3.2.1` please either file a new issue or respond here with code to reproduce it, thanks!
