### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by djputta** [AtomLinter/linter-flake8#289]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

Debug information:
Atom version: 1.10.2
Flake8 version: `2.5.1 (pep8: 1.7.0, pyflakes: 1.3.0, mccabe: 0.3.1) CPython 3.5.2 on Linux`

**Comment by Arcanemagus** [comment]
Please update to the current version of `flake8`, v3.1.0 fixed the error you are likely hitting, and v3.2.1 fixed a positioning bug with that entire class of errors.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still experiencing this after updating to `flake8>=3.2.1` please either file a new issue or respond here with code to reproduce it, thanks!
