### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by djordon** [AtomLinter/linter-flake8#294]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.5
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 2.7.11 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` and try again, v3.1.0 fixed a related error, and v3.2.1 fixed a whole class of errors  like the one you hit.

**Comment by djordon** [comment]
I see. Updating linter-flake8 to version 2.1.3 (from 2.1.1 I think) fixed this.

**Comment by Arcanemagus** [comment]
The version of `linter-flake8` has nothing to do with this issue, this is a bug in the version of `flake8` you have installed. Running `pip install -U flake8` should update you to the current version.

**Comment by djordon** [comment]
I see. When I originally updated `linter-flake8` the issue went away and I couldn't reproduce it for some time but it come back. I updated `flake8` and this issue hasn't resurfaced since.

**Comment by djordon** [comment]
Thanks @Arcanemagus
