### ISSUE TITLE
Atom blocked editing files with plenty of errors

### ISSUE THREAD

**Issue by marianobianchi** [AtomLinter/linter-flake8#295]
I'm working on a new project with some old and no-stylish code and have lots of files with plenty of errors. Whenever I start to edit one of those files (i.e: one with ~400 errors) atom editor freezes for 5 or 6 seconds.

It is not a memory or resources problem. I have 16GB of RAM and a i5 5th generation with 4 cores.

I tried disabling other linters i have installed before (eslint, pep8) but it keep freezing every time i edit the file. I also try to disable linting automatically every 300ms and just lint whenever i save the file. With this latest configuration, i could edit the file without problem but then when i save it had the same problem again.

Watching processes with htop let me see that one atom process was consuming 100% of one core.

Is there anything i'm missing or is a known problem with the linter? Maybe it would be good to set by configuration a maximum errors to be shown. So whenever a file reach that quantity of errors the linter stop searching for problems.

**Comment by Arcanemagus** [comment]
Linter (what handles managing the providers and displaying the messages) handles thousands of messages with no issues. Are you sure it's an `atom` process that is taking the CPU? This package runs `flake8` which is doing all the work, but the UI thread _would_ be blocked while it is running currently.

**Comment by marianobianchi** [comment]
Yes, I'm pretty sure. I attach some pictures to show you this. I took some snapshots of htop output. Take a look at the uptime in both pictures. It took more than 35 seconds to stop processing and let atom responsive again.

I also attach an atom screenshot to show you how many errors flake8 had to process.


![htop_1633](https://cloud.githubusercontent.com/assets/1700075/20911640/0fff1ca2-bb48-11e6-9d72-7bc4b66118d1.png)
![htop_1707](https://cloud.githubusercontent.com/assets/1700075/20911641/10011e12-bb48-11e6-95ab-d6e4e9fa8a88.png)

![atom_errors_hang](https://cloud.githubusercontent.com/assets/1700075/20911676/6aff51e4-bb48-11e6-8654-52a9face3d4f.png)

**Comment by Arcanemagus** [comment]
Can you try running the profiler in Atom ([instructions](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance))? That should give us an idea what is taking so much time within Atom.

**Comment by marianobianchi** [comment]
I tried it but whenever I save a profile it is saved empty. I attach here a picture of the profile chart. I will try to remove ".atom" folder and start from scratch to see what happen.

I add here some data that maybe can help:
$ atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

I'm using webupd8team's Atom PPA.

When I stopped the Profiler I got this error:

> Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

And when I open Atom I got these warnings:

> /opt/atom/resources/app.asar/node_modules/space-pen/lib/space-pen.js:452 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

> /opt/atom/resources/app.asar/src/text-editor-component.js:975 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.


![slow_flake8_linter](https://cloud.githubusercontent.com/assets/1700075/20948159/5bc4afd6-bbf1-11e6-9858-b3b0ad210bf6.png)

**Comment by Arcanemagus** [comment]
The two warnings have been showing in Atom's dev console for a while now, they seem to be related to styling stuff inside Atom? In any case they are ignorable for our purposes.

I should have mentioned that it's a known bug that you can't save the profile, sorry!

Would you be able to provide code that shows this? It looks like this might be a bug in the `extractRange` function that attempts to fix some terrible ranges from the provider.

**Comment by marianobianchi** [comment]
It seems to be something with this linter. I installed linter-pep8 and linter-pyflakes. Get the same amount of errors but while linters are looking for errors Atom doesn't freezes.

**Comment by marianobianchi** [comment]
> I should have mentioned that it's a known bug that you can't save the profile, sorry!
No problem. I just tried a lot to do that because I didn't find any bug reported in github. Can you give me a link to that bug?

> Would you be able to provide code that shows this? It looks like this might be a bug in the `extractRange` function that attempts to fix some terrible ranges from the provider.

I try to remove all the things related to my work place because I shouldn't make this public. I attach here the file that is causing flake8 to freeze atom


[test_flake8.py.zip](https://github.com/AtomLinter/linter-flake8/files/635551/test_flake8.py.zip)

**Comment by Arcanemagus** [comment]
Got it, I'll check it out later today 😉.

**Comment by pferreir** [comment]
I'm also experiencing slowdowns with linter-flake8. The profiler seems to show something similar to what @marianobianchi posted.

![image](https://cloud.githubusercontent.com/assets/2699/21016556/459d0f84-bd66-11e6-9f0a-ab1346852419.png)

The function `importedUnused` seems to be affected in particular.

**Comment by marianobianchi** [comment]
It worked great! Thanks!
