### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by brityboy** [AtomLinter/linter-flake8#299]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: unexpected EOF while parsing`.

import numpy as np
(when it is on the very first line)

Debug information:
Atom version: 1.10.2
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.2.1, pyflakes: 1.1.0) CPython 3.5.2 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
