### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by peterlada** [AtomLinter/linter-flake8#303]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.6
Flake8 version: `2.5.2 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 3.4.4 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by peterlada** [comment]
Awesome, totally worked!
