### ISSUE TITLE
The linter binary 'flake8' cannot be found.

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/linter-flake8#31]
This package gives this error, but if I open a new terminal:

    $ which flake8
    /usr/bin/flake8

**Comment by Yajo** [comment]
Versions:

- atom-0.196.0-0.1.fc21.x86_64
- linter-flake8 1.4.0

**Comment by ChaoticMind** [comment]
Probably a duplicate of #18

**Comment by badray** [comment]
@Yajo Hi, what operating system do you use?

**Comment by Yajo** [comment]
Fedora 21. However, I noticed that after updating to atom-0.198.0-0.1.fc21.x86_64 I have not reproduced this bug.

**Comment by badray** [comment]
Closed as duplicate of #18
