### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by chrisfarnham** [AtomLinter/linter-flake8#321]
Flake8 reported an invalid point for the rule `E999`, with the messge `IndentationError: expected an indented block`.

Debug information:
Atom version: 1.12.7
Flake8 version: `3.0.2 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0, naming: 0.4.1) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by chrisfarnham** [comment]
Cool, it works. Sorry for the unnecessary issue.

**Comment by Arcanemagus** [comment]
No worries 😉.
