### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by yahe** [AtomLinter/linter-flake8#322]
Flake8 reported an invalid point for the rule `E901`, with the messge `TokenError: EOF in multi-line statement`.

Triggered by the following:
    
    import re
    
    def

Debug information:
Atom version: 1.12.7
Flake8 version: `2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, pyflakes: 0.8.1, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1) CPython 2.7.12+ on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by yahe** [comment]
Thanks @Arcanemagus. I believe `flake8` reports a wrong version of `hacking` as I _had_ 0.12 and now I have updated to 0.13. Anyway updating `flake8` to 3.2.1 worked, my bad, thanks a lot!

This is the tail of the output of `flake8` (3.2.1):

     Installed plugins: mccabe: 0.5.3, pyflakes: 1.3.0, hacking.core: 0.0.1,
     ProxyChecker: 0.0.1, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, pycodestyle:
     2.2.0

As you can see `hacking.core` shows up as v0.0.1

**Comment by Arcanemagus** [comment]
Sorry, I meant `hacking` _itself_ is very out of date, not specifically the version of it you have installed. Even the latest v0.13 still has a maximum supported version of `flake8` of `flake8<2.6.0,>=2.5.4`, meaning v3.2.1 isn't compatible.

**Comment by yahe** [comment]
Oh I see. Thanks again @Arcanemagus
