### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by amblock** [AtomLinter/linter-flake8#324]
Flake8 reported an invalid point for the rule `E901`, with the messge `IndentationError: expected an indented block`.

Debug information:
Atom version: 1.12.7
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
