### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by OscBacon** [AtomLinter/linter-flake8#325]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.7
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 3.5.2 on Windows`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by OscBacon** [comment]
Thanks!
This fixed it!
