### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by jason-neal** [AtomLinter/linter-flake8#326]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

#!/usr/bin/python

Debug information:
Atom version: 1.11.2
Flake8 version: `2.5.1 (pep8: 1.7.0, pyflakes: 1.3.0, mccabe: 0.3.1) CPython 3.5.2 on Linux`

**Comment by jason-neal** [comment]
I had a doc string ending with 4 quote marks (""""). Fixing this typo stopped the issue appearing.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Comment by jason-neal** [comment]
Sorry yes it was resolved now thanks.
