### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by SilverWingedSeraph** [AtomLinter/linter-flake8#327]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.
On hashbang line:

`#!/usr/bin/env python3`

Debug information:
Atom version: 1.11.1
Flake8 version: `3.0.4 (pyflakes: 1.2.3, pycodestyle: 2.0.0, mccabe: 0.5.2) CPython 3.5.2+ on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by SilverWingedSeraph** [comment]
Yep! Fixed. Sorry about raising it here.

**Comment by Arcanemagus** [comment]
I'm just glad it's fixed for you ;)
