### ISSUE TITLE
E901 py36 f-strings

### ISSUE THREAD

**Issue by jarekwg** [AtomLinter/linter-flake8#328]
fstrings (introduced in python 3.6) get whacked with E901s:
```
fruit = 'apple'
print(f'I ate this here {fruit}.')
```

**Comment by Arcanemagus** [comment]
This package is simply relaying the results of running `flake8` on the file, are you sure it's running the _right_ `flake8` (if you have it installed for both Python 2.7 and Python 3.6 for example)?

**Comment by jarekwg** [comment]
Oh crap, you're right. Was running py35's flake8. My apologies.

**Comment by Arcanemagus** [comment]
No worries, glad it was a simple fix 😉.
