### ISSUE TITLE
The color combination of warning (white on this specific yellow\red) and error is too bright

### ISSUE THREAD

**Issue by Guy-Markman** [AtomLinter/linter-flake8#333]
In the last version of linter, something changed: 
When I click on a line that is marked as a warning or error, a bar opens. On this bar there is a bright yellow\red mark, and the writing on it is white. Therefore it is not readable. 

Here are pictures of it
![image](https://cloud.githubusercontent.com/assets/22491569/21953873/f84e0c5e-da4a-11e6-88f6-2fcc92e9ab6f.png)
![image](https://cloud.githubusercontent.com/assets/22491569/21953897/f90a6772-da4b-11e6-8dd7-55b4823d1ff5.png)

Please correct it or give us the option to do it ourselves.

**Comment by Arcanemagus** [comment]
This is more a bug with the theme you are using that it has chosen colors that don't work together properly. In any case this is an issue with [Linter](https://github.com/steelbrain/linter/issues) and can't be fixed here.
