### ISSUE TITLE
Flake8 rule 'E202' reported an invalid point

### ISSUE THREAD

**Issue by ek0519** [AtomLinter/linter-flake8#336]
Flake8 reported an invalid point for the rule `E202`, with the messge `whitespace before '}'`.

Debug information:
Atom version: 1.13.0
Flake8 version: `3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment]
Can you provide code to reproduce this? This is a bug in `flake8` which needs to be tracked down and reported there so it can be fixed for everyone using it 😉.

**Comment by Arcanemagus** [comment]
Unfortunately without a sample of code to reproduce this, no further work can be done to track down where this issue ultimately rests. If can come up with a code sample I would be glad to track this down further, for now though I'm going to close this issue.
