### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by freddystban** [AtomLinter/linter-flake8#337]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.13.0
Flake8 version: `2.5.0 (pep8: 1.5.7, pyflakes: 1.0.0, mccabe: 0.3.1, naming: 0.3.3) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by freddy-perez** [comment]
thank you, sorry

**Comment by Arcanemagus** [comment]
No worries, glad that fixed it for you 😉.
