### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by adamysu** [AtomLinter/linter-flake8#339]
Flake8 reported an invalid point for the rule `E901`, with the message `SyntaxError: invalid syntax`.

import os

Debug information:
Atom version: 1.13.0
Flake8 version: `2.2.5 (pep8: 1.5.7, mccabe: 0.2.1, pyflakes: 0.8.1) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by dbstraffin** [comment]
I had the same problem.  Updating flake8, as suggested, fixed it.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response from @adamysu, if you are still having issues after updating `flake8` please provide code to reproduce this!
