### ISSUE TITLE
Python Django Can Not be Recognised

### ISSUE THREAD

**Issue by pingshunhuangalex** [AtomLinter/linter-flake8#343]
I noticed that when atom recognises my python file as `Python Django`, `linter-flake8` will just stop working. As long as I manually change it back to `Python`, it'll start working again. Could you please fix this issue by generalising the file type or at least let user set the dictionary themselves. Thanks.

**Comment by Arcanemagus** [comment]
"Python (Django)" should already be supported ([part 1](https://github.com/AtomLinter/linter-flake8/blob/v2.1.4/lib/main.js#L140), [part 2](https://github.com/AtomLinter/linter-flake8/blob/v2.1.4/package.json#L17-L18)).

What language package are you using that is forcing Atom to recognize the file as Django instead of regular Python?

**Comment by pingshunhuangalex** [comment]
Hi @Arcanemagus 
Hmm.. That's weird.
The only django package I'm using is `atom-language-django` (not many out there anyway.) Here are the screenshot:
![image](https://cloud.githubusercontent.com/assets/17170199/22808956/1de18a98-ef83-11e6-8623-08a4d1057eb4.png)
![image](https://cloud.githubusercontent.com/assets/17170199/22808980/42c78ca4-ef83-11e6-99ca-2975983efb13.png)

And I noticed that all the python related file type I got have duplicates... Now I'm really confused...
![image](https://cloud.githubusercontent.com/assets/17170199/22809015/824311be-ef83-11e6-8bc5-df59ae6cb3ab.png)

**Comment by pingshunhuangalex** [comment]
Hi @Arcanemagus 
Never mind, after I clear the cache, disable and re-enable the `language-django` package. Everything seems to work now and duplicates are also gone. Could be just those weird cache issue...

**Comment by pingshunhuangalex** [comment]
Sorry duplicates are gone, but the issue remains... I jumped to the conclusion there.

**Comment by pingshunhuangalex** [comment]
Hi @Arcanemagus 
Sorry for all the spamming. It works on all new files after I cleared the cache. It's just won't work on that file that's already opened. Weird cache issues. Thanks for being patient.

**Comment by Arcanemagus** [comment]
Glad you got it worked out!
