### ISSUE TITLE
E501 and `editor.preferredLineLength`

### ISSUE THREAD

**Issue by pohmelie** [AtomLinter/linter-flake8#344]
It looks like linter-flake8 does not respect `editor.preferredLineLength`, since I have per project options, but linter-flake8 did both my projects with different `editor.preferredLineLength` as it is 0 or not setted.

**Comment by Arcanemagus** [comment]
You need to set `linter-flake8.maxLineLength`, not `editor.preferredLineLength`. I'm not entirely sure _why_ it's a separate setting, but it is.

**Comment by pohmelie** [comment]
@Arcanemagus, yep, that works, thanks!
