### ISSUE TITLE
Possible Coloring Issue?

### ISSUE THREAD

**Issue by pingshunhuangalex** [AtomLinter/linter-flake8#347]
Hi @Arcanemagus 

Not sure if this is flake8 related or theme related...

As shown in the below screenshot, I noticed the text in warning tooltips in flake8 is really hard to see. I guess it's probably the material-ui theme I'm using that's causing the issue, but I also know some lintering have their own custom styling. So just wonder if it's flake8's issue here. If it is, hope it can be resolved. Thanks.

![image](https://cloud.githubusercontent.com/assets/17170199/22853728/d2e6fa0c-f0b1-11e6-8fdf-03a35e73fa63.png)

**Comment by Arcanemagus** [comment]
This provider doesn't have any styling, so it's whatever the default Linter uses. In this case I'd say it's a theme issue since that combination should work fine. In any case either way it's not something that is handled here.

**Comment by pingshunhuangalex** [comment]
Thanks. Already reported to the Theme provider. Just want to make sure here.

**Comment by Arcanemagus** [comment]
Hmmm, actually it looks like this is on Linter, see [here](https://github.com/steelbrain/linter/blob/v1.11.21/styles/linter-plus.less#L165). It seems that @steelbrain is forcing the text color to be `white` for some reason.

**Comment by pingshunhuangalex** [comment]
Thanks @Arcanemagus Will open another issue in `Linter` to see how it goes.
