### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by jc09987** [AtomLinter/linter-flake8#348]
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

Debug information:
Atom version: 1.14.1
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment]
Are you able to share the file that triggers this? Or can you come up with a minimal reproduction case?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If you can provide a file to reproduce this I'd be happy to investigate the root cause!
