### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by mbaxa** [AtomLinter/linter-flake8#352]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

This happened on line 1:
```python
#!/usr/bin/env python3
```

Debug information:
Atom version: 1.14.3
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.4.0, pyflakes: 1.0.0) CPython 2.7.13 on Darwin`

**Comment by mbaxa** [comment]
This comes and goes; after making a minor change to the file that didn't include syntax, the error disappeared.

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by mbaxa** [comment]
Done, I haven't seen it since
