### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Vitjoc** [AtomLinter/linter-flake8#358]
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (132 > 79 characters)`.

Debug information:
Atom version: 1.13.1
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.0 on Windows`

**Comment by Arcanemagus** [comment]
Are you able to share code to reproduce this?

There is currently a known bug with unicode characters that _might_ be causing this, but without code it's impossible to say.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you can share code to reproduce this I would be happy to look into it further!
