### ISSUE TITLE
Flake8 rule 'E502' reported an invalid point

### ISSUE THREAD

**Issue by jplaza** [AtomLinter/linter-flake8#360]
Flake8 reported an invalid point for the rule `E502`, with the messge `the backslash is redundant between brackets`.

Debug information:
Atom version: 1.14.3
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment]
Are you able to share code to reproduce this? There is a known bug with UTF8 characters, but without code to reproduce it is impossible to know where the problem is here.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you can share code to reproduce this I would be happy to look into it further!
