### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by MidnightCitizen** [AtomLinter/linter-flake8#365]
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (80 > 79 characters)`.

"""Zod Style Game (Exercice 36).""" at the start of the python file

Debug information:
Atom version: 1.15.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.0 on Windows`

**Comment by Arcanemagus** [comment]
Are you able to share code to reproduce this?

There is currently a known bug with unicode characters that _might_ be causing this, but without code it's impossible to say.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, it's very likely that [pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306) is the true problem here.
