### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by YuhoOba** [AtomLinter/linter-flake8#366]
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

Debug information:
Atom version: 1.15.0
Flake8 version: `3.2.1 (pyflakes: 1.3.0, mccabe: 0.5.2, pycodestyle: 2.2.0) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment]
Are you able to share code to reproduce this?

There is currently a known bug with unicode characters that _might_ be causing this, but without code it's impossible to say.

**Comment by YuhoOba** [comment]
It can be reproduced with the following code.

```
import jaconv


class Foo():

    @staticmethod
    def _create_option_object(position, entry_name, value, is_size=False):
        return {
            'position': position,
            'entry_name': entry_name,
            'value': jaconv.h2z(value) if value else None,
            'is_size': is_size,
            }

    @staticmethod
    def _concat_names(sep, names):
        str = None
        for name in names:
            if not str and name is not None and name.strip() is not '':
                str = name
            elif name is not None and name.strip() is not '':
                str += '%s%s' % (sep, name.strip())
        return str

    def bar(self):
        # do something
        return {
            'options': [
                self._create_option_object(1, 'テスト', self._concat_names('',[
                    None,
                    'test',
                    ]), True),
            ],
        }
```
If 'テスト' is changed to one character by Unicode character like 'テ' or when it is changed to ASCII character, it does not occur,
It may concern you bugs.

**Comment by Arcanemagus** [comment]
Ah ha! Thanks for providing the code.

This is another case of [pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306) which is fixed on their `master` branch and should be in the next `flake8` release. Unfortunately there isn't anything that can be done here till then 😞.

**Comment by YuhoOba** [comment]
I understand. Thank you.
