### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by abovethecloud** [AtomLinter/linter-flake8#369]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.15.0
Flake8 version: `2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, pyflakes: 0.8.1, flake8-docstrings: 1.0.3, pydocstyle: 1.1.1) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by abovethecloud** [comment]
Indeed this fixed it. Thank you.
