### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by dmbasso** [AtomLinter/linter-flake8#37]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (/usr/share/atom/resources/app.asar/src/package.js:790:9)
Package.hasActivationCommands (/usr/share/atom/resources/app.asar/src/package.js:715:20)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:169:24)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
```

**Comment by dmbasso** [comment]
Oops, I should have searched the closed issues, this one is a duplicate. But the original should be reopened, as this is still happening in version 1.4.0.

**Comment by Arcanemagus** [comment]
It's still happening in 1.4.0 because apparently they still haven't released a version that includes the fix :unamused:.

https://github.com/AtomLinter/linter-flake8/compare/v1.4.0...master

**Comment by badray** [comment]
@dmbasso @Arcanemagus I'll release a version with fix in minutes.

**Comment by Arcanemagus** [comment]
@badray Thanks!

**Comment by dmbasso** [comment]
@badray Thank you. I'm curious to see what actually is the problem, because the `activationCommands` was defined in the `package.json`, though it was an array instead of an object. Could that be the cause?

**Comment by Arcanemagus** [comment]
@dmbasso This is the commit that fixes this issue: https://github.com/AtomLinter/linter-flake8/commit/53b8d3bbdf98884f9e3be4a6b701eb3d6ee03313

**Comment by dmbasso** [comment]
Now I understand, the fix was accepted long ago, only it was not `apm publish`ed. I've seen that commit before, that's why I mentioned the possible array/object issue.

**Comment by badray** [comment]
No problem :).

@dmbasso Ok I didn't know what you mean :D, as @Arcanemagus clearly said that fix wasn't released yet :).

**Comment by Arcanemagus** [comment]
Duplicate of #29.
