### ISSUE TITLE
Flake8 rule 'W292' reported an invalid point

### ISSUE THREAD

**Issue by notionparallax** [AtomLinter/linter-flake8#370]
Flake8 reported an invalid point for the rule `W292`, with the messge `no newline at end of file`.

https://github.com/notionparallax/code1161base/blob/c893bf0280a2e2823d77a3675303b3cf3e72a3d5/codeHelpers.py 

Debug information:
Atom version: 1.14.3
Flake8 version: `3.2.0 (mccabe: 0.5.3, pyflakes: 1.3.0, hacking.core: 0.0.1, ProxyChecker: 0.0.1, flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, pycodestyle: 2.2.0) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment]
Thanks for providing the code! I see non-ascii characters in there, so I'm almost positive this is [pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306) which has been fixed on their `master` but unfortunately isn't released yet.
