### ISSUE TITLE
[Linter] Error running Flake8

### ISSUE THREAD

**Issue by Bonjew** [AtomLinter/linter-flake8#372]
When I open a python file, it comes out an error and the Flake8 does not work.

```
[Linter] Error running Flake8
See console for more info
```
When I disabled the "linter" package and open a python file, the error had gone. But the Flake8 still did not work.

I google for a long time and still do not know what the problem is.

**Comment by Bonjew** [comment]
The Flake8 works inPyCharm. I find that the pip of python2.7 has been disappeared in my computer, and there is only pip3 of python3.5 can be used.

**Comment by Bonjew** [comment]
When I used pip3 freeze, it came out the flake8 version.
But I used the command line to find flake8, the flake8 was not found：

```
$ which flake8
flake8 not found
```

**Comment by Bonjew** [comment]
The Shell I am using is Zsh. I just changed my shell to Bash. the commands,such as pip, pip3, which, all did work. I used "$ which flake8" and found the path is "/Library/Frameworks/Python.framework/Versions/3.5/bin/flake8".

I put the dir into the Settings>Executable Path, and the linter-flake8 works.

**Comment by Bonjew** [comment]
1. Copy the settings in the .bash_profile to the end of the .zshrc. (.bash_profile is the settings file of Bash, .zshrc is the settings file of Zsh)

```
# Setting PATH for Python 3.5
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH
```

2. Restart the terminal.

pip, pip3, which do work.

**Comment by Gowtham-Sridhar** [comment]
Try this:
  firstly, uninstall the 'linter-flake8' package in atom editor ( Edit > Preference > Packages > linter-flake8 > uninstall )

then, open your terminal and type 
`sudo pip3 install flake8`

You can then install this package from with Atom or by typing:
`apm install linter-flake8`

then, restart your atom editor, "BOOM" .. the linter works perfectly. 
hope this helps you out.
