### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by lukeSkywallk** [AtomLinter/linter-flake8#375]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: EOF while scanning triple-quoted string literal`.

Debug information:
Atom version: 1.15.0
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 2.7.12+ on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by lukeSkywallk** [comment]
Thank you very much.

2017-03-23 18:50 GMT-03:00 Landon Abney <notifications@github.com>:
