### ISSUE TITLE
Flake8 extremely slow and sometimes makes Atom unresponsive

### ISSUE THREAD

**Issue by danqing** [AtomLinter/linter-flake8#376]
I'm not sure if this is a flake8 issue or a linter issue, but mostly after linter got updated to 2.x, flake8 becomes extremely laggy. It works fine with other linters though (eslint, for example), so I suspect something is going on with flake8.

I'm on the latest: linter 2.1.2, linter-flake8 2.1.5, atom 1.15.0, sierra 10.12.3.

Not seeing any issues opened for this, so not sure if it's just me or if other people are seeing similar issues.

**Comment by dengemann** [comment]
I have the same issue. Flake8 became unusable to me. Is there a way to deactivate the on-the fly checking?

**Comment by Arcanemagus** [comment]
@dengemann You can disable on the fly checking in the settings for the Linter package itself. `linter-flake8` is simply a provider for that.

@danqing Nothing should have changed with the update to Linter v2 with regards to this, the only semi-relevant thing would be that the customizable delay for lint-on-change got reset so you may be triggering more often than expected?

**Comment by Arcanemagus** [comment]
I'm going to close this as #412 should take care of the problem of multiple `flake8` processes running at once, which is _likely_ the problem you are hitting here. If things are not better after the upcoming release of this provider please let me know!

**Comment by jaimemarijke** [comment]
I seem to be having the same problem: it lints on the fly, but it takes 3-4 seconds to actually do so. I never notice this kind of lag with linter-eslint, so it seems specific to linter-flake8.

Versions: linter 2.2.0, linter-flake8 2.3.0, atom 1.29.0, Mac OS X High Sierra 10.13.6

**Comment by matthen** [comment]
(I get the same issue as @jaimemarijke)
