### ISSUE TITLE
Flake8 rule  E901  reported an invalid point

### ISSUE THREAD

**Issue by p5eudo** [AtomLinter/linter-flake8#377]
Flake8 reported an invalid point for the rule  E901 , with the messge  SyntaxError: unexpected EOF while parsing .

Debug information:
```
Atom version: 1.14.1
Flake8 version:  2.5.4, pep8: 1.7.0, pyflakes: 1.1.0, mccabe: 0.2.1  CPython 3.5.2 on Linux
```

This error appears almost every time I start writing a python script in Atom. What code I write seems to be irrelevant. This is all I've typed currently, which produced the error:

`class animal(object):`

(possibly) SOLVED: used terminal command `pip install flake8`, which updated flake8 and uninstalled some old pyflakes code. Fired up Atom after, and the error was gone.

**Comment by Arcanemagus** [comment]
That's definitely solved 😉.

Versions of `flake8` before v3.2.1 had a bug in all `E9xx` errors that caused them to report the wrong position by one character. It seems nobody had noticed till that check was put in place here and reported/fixed there.

Thanks for taking the time to report it!
