### ISSUE TITLE
Max Line Length default value is 79

### ISSUE THREAD

**Issue by MarvBob** [AtomLinter/linter-flake8#379]
I would like to disable the max line length verification, so I did not write any value in the Max Line Length parameter in the Settings panel and it says "Default: 0" which I guess means no max line length, but I have an E501 (line too long) warning when the line is >79 characters.
As the default value is zero, if I try to set the field to zero, it is replaced by "Default: 0" and does not change anything.
I think that a max line length zero value should disable the max line length verification, and the default value indicated in the settings should indicate its "real" value.

**Comment by Arcanemagus** [comment]
The default value of 0 means we [don't specify](https://github.com/AtomLinter/linter-flake8/blob/6b8247ecc3814aa90db11445ae0f8840d52962c8/lib/main.js#L156) any value to `flake8`... which means the _`flake8`_ default of 79 characters is used. Maybe this could be made clearer in the setting description?

**Comment by MarvBob** [comment]
I think the default value should not be 0 then but 79 and we should be able to set 0 to disable the max line length

**Comment by Arcanemagus** [comment]
As far as I can tell from [the documentation](https://flake8.readthedocs.io/en/latest/user/options.html#cmdoption-flake8--max-line-length), that's not how that option works. You either specify a value, or it defaults to `79`.

**Comment by MarvBob** [comment]
Yes that is how it seems to work, but I think the problem is that when you don't specify a value it says "Default: 0" but the default value is 79.

**Comment by Arcanemagus** [comment]
Do you think changing the default to 79 will be clear enough? Or should a description be added as well?

**Comment by MarvBob** [comment]
I think changing the default value will be clear enough, and if setting a zero value could disable the max line length that would be nice.

**Comment by Arcanemagus** [comment]
That would have to be implemented in `flake8` (Or I think `pycodestyle` which `flake8` is wrapping) 😉. I'll put up a PR implementing this shortly.
