### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Redjumpman** [AtomLinter/linter-flake8#384]
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (101 > 100 characters)`.

![image](https://cloud.githubusercontent.com/assets/18455011/24560231/8045eea4-1607-11e7-8712-92b80589a351.png)

[Hastebin](https://hastebin.com/uyezetuzab.py)

I'm trying to refactor some old code, and I'm getting the above error. It happens with some of my work, but not all of it. I've been trying to track down what triggers that from happening, but I can't seem to narrow it down. I included a screenshot and a hastebin since I didn't want to put 500 lines of code in here. Any help would be much appreciated.

Debug information:
Atom version: 1.15.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.5.3 on Windows`

**Comment by Arcanemagus** [comment]
Does the file in question have any Unicode characters? There is currently a bug ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)) causing issues with files that have Unicode characters in them. If you aren't sure and are able to share the file I can take a look for you.

**Comment by Redjumpman** [comment]
I'm not 100% sure, but I included a hastebin of the entire code.

**Comment by Arcanemagus** [comment]
Hmmm, I actually can't reproduce this with the file you posted on the following version:
```json
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "28.8.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.1",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "plugin": "pyflakes",
      "version": "1.5.0"
    }
  ],
  "version": "3.3.0"
}
```

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
