### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by tymokvo** [AtomLinter/linter-flake8#385]
Flake8 reported an invalid point for the rule `E901`, with the messge `IndentationError: expected an indented block`.

code:

`import numpy as np`

on line 1

Debug information:
Atom version: 1.15.0
Flake8 version: `2.6.2 (pycodestyle: 2.0.0, mccabe: 0.5.0, flake8-docstrings: 0.2.8, pep257: 0.7.0, pyflakes: 1.2.3) CPython 2.7.6 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by tymokvo** [comment]
yep seems to be fixed. thanks!
