### ISSUE TITLE
Flake8 rule 'F821' reported an invalid point

### ISSUE THREAD

**Issue by gm2bv** [AtomLinter/linter-flake8#389]
Flake8 reported an invalid point for the rule `F821`, with the messge `undefined name 'case'`.

Debug information:
Atom version: 1.15.0
Flake8 version: `3.2.1 (pycodestyle: 2.2.0, pyflakes: 1.3.0, mccabe: 0.5.3) CPython 3.5.2 on Darwin`

**Comment by Arcanemagus** [comment]
There is currently a bug ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)) causing issues with files that have Unicode characters in them. If you don't think this fits your situation please upload a file to check on this!

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
