### ISSUE TITLE
Flake8 rule 'F821' reported an invalid point

### ISSUE THREAD

**Issue by JamesDoone** [AtomLinter/linter-flake8#397]
Flake8 reported an invalid point for the rule `F821`, with the messge `undefined name 'time'`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Darwin`

**Comment by Arcanemagus** [comment]
There is currently a bug ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)) causing issues with files that have Unicode characters in them. If you don't think this fits your situation please upload a file to check on this!

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
