### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by foresmac** [AtomLinter/linter-flake8#400]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.16.0
Flake8 version: `2.6.2 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.0) CPython 2.7.11 on Darwin`

**Comment by foresmac** [comment]
![screen shot 2017-04-20 at 4 40 10 pm](https://cloud.githubusercontent.com/assets/3628189/25253832/31dc72e2-25e8-11e7-94f2-038a0fa55667.png)

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by foresmac** [comment]
@Arcanemagus Updated. I have not seen the issue return. Thanks!
