### ISSUE TITLE
[Linter] Error running Flake8

### ISSUE THREAD

**Issue by MikeRoma** [AtomLinter/linter-flake8#403]
I did a little research before posting this and have the exact same error of this topic:
https://github.com/AtomLinter/linter-flake8/issues/372

> [Linter] Error running Flake8
> See console for more info

However I am already using Bash as shell so I don't have a clue on how to fix it.
I tried removing the Linter and Flake8 packages and installing them from the console but nothing.

Also when I look for $ which flake8 I don't get anything back from the console after being installed.

**Comment by Arcanemagus** [comment]
If `which flake8` isn't returning anything, then wherever `pip` installed it for you isn't in your `$PATH`. You _can_ use this setup, you will just need to set the path manually in the settings.

You'll need to open _Atom's_ Developer Tools, then go to the Console tab to see the actual error output.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems please provide the information requested!

**Comment by jbonefish** [comment]
I keep getting this same error (below).  when I search for Flake8 I find nothing - any suggestions?  It's driving me batty.  many error messages every time I make any code changes.  Thanks for any suggestions!

"[Linter] Error running Flake8 Error: Failed to spawn command `flake8`. Make sure `flake8` is installed and on your PATH
    at /Users/jasonhawthorne/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.js:130:24
    at process._tickCallback (internal/process/next_tick.js:103:7)"

**Comment by Arcanemagus** [comment]
@jbonefish Read the previous comments in this thread 😉.

**Comment by waldemar93** [comment]
Hello, I am having the same issue with atom. I have installed all the predetermined specifications but I seem to have lost the path to my linter-flake8. I have tried various inputs in settings and it always strikes the same error .  Anywhere I can locate the pathway? Thanks

**Comment by Arcanemagus** [comment]
@waldemar93 Please read the previous messages in the thread. You **must** install `flake8` before attempting to use `linter-flake8`, as this is a wrapper around that tool.

Instructions can be found on [their site](http://flake8.pycqa.org/en/latest/index.html#quickstart).
