### ISSUE TITLE
Setting to ignore or specify configuration file?

### ISSUE THREAD

**Issue by pjuren** [AtomLinter/linter-flake8#41]
At present, it seems as if linter-flake8 looks for a configuration file in the CWD (or higher) and tries to use this to configure flake8. If it finds one, then the options entered in the editor settings panel are ignored in favour of the file. The files searched for are 'setup.cfg', 'tox.ini', and '.pep8', in that order. 

I have projects where there is a setup.cfg in the root of the project, but this file is for a different purpose. Its presence seems to cause linter-flake8 to ignore the settings I've provided in favour of that, but I can't use this filename for actually configuring flake8, and because it is the first filename in the search order, it seems I can't provide something else (e.g. '.pep8') instead. At present, I can't use the linter for those projects because I need to ignore some rules.

Am I missing some simple workaround for this? If not, it might be nice to allow users to either (1) specify that they want to ignore all configuration files; or (2) that they want a particular search order; or (3) that they have a particular name for their configuration files.

**Comment by badray** [comment]
@pjuren There is no simple workaround for this right now. I think I'll implemented option (3) before next release.

Thanks for your time.
