### ISSUE TITLE
Flake8 rule 'F821' reported an invalid point

### ISSUE THREAD

**Issue by jarekwg** [AtomLinter/linter-flake8#415]
Flake8 reported an invalid point for the rule `F821`, with the messge `undefined name 'key'`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.0 on Darwin`

**Comment by jarekwg** [comment]
Atom told me to report this issue, feel free to close if it's not important, or lemme know if you need more context. Just happened today when I bumped all my packages.

**Comment by Arcanemagus** [comment]
There is currently a bug ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)) causing issues with files that have Unicode characters in them. If you don't think this fits your file please upload a sample so we can get this figured out!

**Comment by jarekwg** [comment]
Yep, fits.
Cheers,
