### ISSUE TITLE
Ignore Error Codes not working

### ISSUE THREAD

**Issue by chrisjlebron** [AtomLinter/linter-flake8#43]
Attempts to ignore E126 (over-indented line) warnings do not work. I work in a shared code base and am not able to do huge whitespace commits without hearing it from my teammates. However, since Linter no longer supports hiding the status bar errors, now half of my screen is taken up by these errors. Just looking for a way to silence them, as these errors are littered throughout the projects I'm working on.

Happy to provide more info to help debug.

**Comment by ChaoticMind** [comment]
Do you have anything written under "selectErrors" in the settings?

**Comment by chrisjlebron** [comment]
@ChaoticMind no, the only fields i've changed were the executable dir, max line length, and the ignore error codes field.

**Comment by badray** [comment]
Hi @chrisjlebron could you post screenshoot of your settings?

**Comment by chrisjlebron** [comment]
@badray See below. I'm unable to ignore any error codes, actually, but this is the one I'm currently attempting to ignore.

![image](https://cloud.githubusercontent.com/assets/596220/8331712/c077d5bc-1a57-11e5-8b76-487ec72456db.png)

**Comment by jmagnusson** [comment]
Same here with a clean install of `atom 1.0.0` + `linter` + `linter-flake8`.

My settings:
![screen shot 2015-06-28 at 01 15 31](https://cloud.githubusercontent.com/assets/190835/8394352/3d5f3e16-1d33-11e5-8c2a-7448da489f56.png)

**Comment by badray** [comment]
@chrisjlebron For me it's working like a charm - E126 is skipped in error list. It looks like you have config file which overrides plugin settings. This behaviour should documented... 
Please give feedback if adding E126 to ignored warning into config file solved your problem.

@jmagnusson Thx for contribution and pointing out core of the problem, but IMO I will merge to project this solution https://github.com/pjuren/linter-flake8/commit/8a56f4ac571db38908865ad6493d0686e4c80794  It is a bit more elastic, as we can use whatever name of config.

**Comment by jmagnusson** [comment]
Sure, as long as it works! :wink:

**Comment by Arcanemagus** [comment]
Marking this as closed, the configuration option seems to be working for me and there is now support for specifying a project configuration file.

If you are still having issues feel free to comment here and we can try to debug what is going on.

**Comment by Cyan4973** [comment]
Same problem here.
No way to remove an annoying flake8 error (E241) while using "ignore error codes" input box.

> It looks like you have config file which overrides plugin settings. 

I have no configuration file (that I'm aware of).
