### ISSUE TITLE
linter marks tuple unpacking as invalid syntax

### ISSUE THREAD

**Issue by alanbato** [AtomLinter/linter-flake8#432]
Whenever you try to unpack a tuple by using the * operator, the linter throws an E999 SyntaxError error.

For example:
```py
foo, bar, *rest = data
```
or
```py
foo(*bar)
```

**Comment by Arcanemagus** [comment]
Are you executing the _right_ `flake8`? It will adopt itself based on the Python version it is executing under, so if you are running it under Python 2.x it will give you odd things like this.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

**Comment by alanbato** [comment]
Sorry, I didn't see your answer. I will check it out, thanks!

**Comment by Arcanemagus** [comment]
Closing (again 😛) due to lack of response.
