### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by frederick-ustc** [AtomLinter/linter-flake8#434]
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment]
Do you have any unicode characters in your file? There is currently a known bug with how those are handled ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)). It's fixed in their `master` branch and is just waiting on a release.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you think the above bug doesn't match your situation please provide some example code to test this with, thanks!
