### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by heron182** [AtomLinter/linter-flake8#437]
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

`# -*- coding: utf-8 -*-
VATLAS_GROUP = 'HP APPS - ATLAS'
VATLAS_SERVICE = 'VATLAS'
VATLAS_CATEGORIES = [u'VATLAS', u'VSMS']

VATLAS_AREA_SUBAREA = {
    (u'TERMINAIS', u'ERROS NA TROCA DE TERMINAIS'): (VATLAS_GROUP, VATLAS_SERVICE),
    (u'TERMINAIS', u'ERROS NA ENTREGA DE TERMINAIS'): (VATLAS_GROUP, VATLAS_SERVICE),
    (u'TERMINAIS', u'ERROS NA DEVOLUÇÃO DE TERMINAIS'): (VATLAS_GROUP, VATLAS_SERVICE),
    ... more dict keys here 
    (u'EQUIPAMENTOS', u'ERRO AO REALIZAR CONTESTAÇÃO'): (VATLAS_GROUP, VATLAS_SERVICE),
}`

Debug information:
Atom version: 1.16.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.5.2 on Windows`

**Comment by Arcanemagus** [comment]
There is currently a known bug with how unicode characters are handled ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)) in `flake8`. It's fixed in their `master` branch and is just waiting on a release. Nothing that can be done about it here unfortunately!
