### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by SiteReliabilityEngineering** [AtomLinter/linter-flake8#438]
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Windows`

**Comment by Arcanemagus** [comment]
Do you have any unicode characters in your file? There is currently a known bug with how those are handled ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)). It's fixed in their `master` branch and is just waiting on a release.

**Comment by SiteReliabilityEngineering** [comment]
Hello. Thank you for the answer. My apologies, it's not happening again. It's strange! Yes, and it haves unicode chars.

**Comment by Arcanemagus** [comment]
It would be a "random" error that would only show up when it's trying to send a message related to the end of the line or the end of the file. `W291` relates to the end of the line so it triggers this pretty often.

I can't wait till they release an update with that fix :(
