### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by bqUAB** [AtomLinter/linter-flake8#443]
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

Debug information:
Atom version: 1.17.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Windows`

**Comment by Arcanemagus** [comment]
Do you have any unicode characters in your file? There is currently a known bug with how those are handled ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)). It's fixed in their `master` branch and is just waiting on a release.

**Comment by bqUAB** [comment]
Probably, I erased all the carry return white spaces and entered them again
by hitting enter and it fixed the problem.
