### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Ars2014** [AtomLinter/linter-flake8#444]
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (120 > 79 characters)`.

`# _*_coding:utf-8;_*_`

Debug information:
`Atom version: 1.16.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.0 on Windows`

**Comment by Arcanemagus** [comment]
There is currently a known bug with how unicode characters are handled ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)). It's fixed in their `master` branch and is just waiting on a release of `flake8`.
