### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by l4zz** [AtomLinter/linter-flake8#445]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

trying to work out the best way to split the following into 2 lines, was deleting the wrapping parenthesis when it crashed:
            if (one['colony_name'] == genotype['genotype'] and
                not matchingValues(tp, one, genotype)):

Debug information:
Atom version: 1.17.0
Flake8 version: `3.0.3 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 3.5.2 on Windows`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
