### ISSUE TITLE
Allow to ignore absence of a flake8 executable

### ISSUE THREAD

**Issue by remcohaszing** [AtomLinter/linter-flake8#446]
I use flake8 installed in virtualenvs to lint my projects. However, sometimes I open a Python file in Atom that's not in a project I've set up a virtualenv for. In this case I don't want flake8 to even run.

I tried to make this plugin ignore that use case by adding `/bin/true` to the executable path, but that still made the Atom console pop up without any actual errors.

Could you add an option to ignore any errors if the executable can't be found?

**Comment by ddaanet** [comment]
I do not think that would be a good idea. Not finding the executable is usually a configuration error, and it needs to be reported to the user.

What do you mean by "made the Atom console pop up". Do you mean the linter pane, not the debugging console? If that's the case, that is a matter of configuring `linter-ui-default`.

If you want to use a different configuration by default and in projects, you can use the `project-manager` package to set project-specific settings.

**Comment by Arcanemagus** [comment]
Absolutely a wontfix here, there is no way for this package to know that you _purposely_ have broken it, instead of somebody just unintentionally breaking the configuration.

**Comment by remcohaszing** [comment]
I don't want a flake8 installed using Python 3.6 to lint Python 2.7 system files when I open those or the other way around. This is why I would like to be able to disable flake8 for system files or files that are part of a virtualenv, not a project.

I'll open another issue about the atom console.

**Comment by Arcanemagus** [comment]
@remcohaszing Maybe we aren't understanding your use case here, so how would you propose this be solved?

From what I'm understanding so far you want:
* A magical way to know when you have a `virtualenv` setup
* When you _don't_ have one setup, the plugin to be entirely non-functional

I don't know of anyway to do the first that handles all the crazy edge cases of all the different "virtual environment" programs people use out there, and the second makes no sense to me personally.
