### ISSUE TITLE
Setting the flake8 executable to /bin/true makes the console pop up

### ISSUE THREAD

**Issue by remcohaszing** [AtomLinter/linter-flake8#452]
I've tried setting `/bin/true` as a fallback for the flake8 executable. However, this makes the Atom debugging console pop up with an uncaught error and no stack trace.

This console pops up every time when flake8 should run.
![screenshot_2017-05-30_20-45-20](https://cloud.githubusercontent.com/assets/779047/26599608/73f1ea6c-4579-11e7-9aec-57d97f476234.png)

**Comment by ddaanet** [comment]
Okay. Here's what seems to be the problem: Atom spawn the subprocess (/bin/true) with stdin set to a fifo. Then /bin/true does no read any input and terminates with success. Then Atom writes to the fifo, but it is closed, so it fails with EPIPE.

Heres the fix: do not use /bin/true. Write a small shell script that ignores any input and exists with success. Something like:
```
#!/bin/sh
exec cat > /dev/null
```
