### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by vatsalgit** [AtomLinter/linter-flake8#455]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: unexpected EOF while parsing`.

Debug information:
Atom version: 1.17.0
Flake8 version: `3.0.4 (mccabe: 0.5.3, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 3.5.2 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
