### ISSUE TITLE
why doesn't work

### ISSUE THREAD

**Issue by hover-cheng** [AtomLinter/linter-flake8#456]
atom 1.17.2 ia32 the linter-flake8 doesn't work

**Comment by beatrizuezu** [comment]
I have the same problem

```
linter-flake8:: Flake8 threw an error related to: AttributeError: 'module' object has no attribute 'PEP257Checker' Please check Atom's Console for more details
```

**Comment by Arcanemagus** [comment]
@beatrizuezu I'm guessing you have a missing or improperly installed extension for `flake8`. As the message tells you the full details are in Atom's Developer Tools's Console.

@hover-cheng I'll need a bit more information than "doesn't work". Are you getting an error message?

**Comment by Arcanemagus** [comment]
I'm guessing from the "ia32" that you are on Windows.

* What do you see when you run `flake8` from the CLI that leads you to think there should be a message?
* Can you run the "Linter: Debug" command and check that `linter-flake8` is enabled on that file?

**Comment by hover-cheng** [comment]
@Arcanemagus I uninstall the "1.17.2 ia32" and install "1.17.2 X64" then  the problem is solved,thank you

**Comment by Arcanemagus** [comment]
Glad to hear it!
