### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by rhagman** [AtomLinter/linter-flake8#459]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

#!/usr/bin/env python

Debug information:
Atom version: 1.15.0
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 1.1.0, mccabe: 0.2.1) CPython 3.5.2 on Linux`

**Comment by rhagman** [comment]
This seems to be an issue with a byte order mark (BOM) at the beginning of the file. A workaround for the issue was to open the file in vim and remove the BOM with 'set nobomb'

**Comment by ddaanet** [comment]
Try again with the latest flake8 (3.3.0), pyflakes (1.5.0) and pycodestyle (2.3.1).

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
