### ISSUE TITLE
Uninstall does not work

### ISSUE THREAD

**Issue by michaelaye** [AtomLinter/linter-flake8#46]
Clicked Uninstall several times, does not work.

Atom 1.0 on Mac OSX 10.10.3

**Comment by badray** [comment]
Also `Atom 1.0` on `Mac 10.10.3`- uninstall works for me. Try looking into developers console for some errors?
I also noticed that when i click, `osx keychain` ask me for a permission to authorize, maybe this is permission issue with your `keychain`?

I have a Polish version of OSX but this may help you - This is screenshoot of keychain permission dialog that have appeared to me when I was uninstalling plugin.
![img](https://dl.dropboxusercontent.com/u/30735923/Zrzut%20ekranu%202015-06-30%2010.47.39.png)

**Comment by badray** [comment]
@michaelaye I would be happy to hear any feedback.

**Comment by michaelaye** [comment]
I never required a password to install Atom packages and I shouldn't, as everything should go to `~/Library` and not `/Library`. However, it might have been a temporary hickup with the Atom API, because after restarting Atom your package was indeed uninstalled. Thanks!

**Comment by badray** [comment]
:+1:
