### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by madHatter106** [AtomLinter/linter-flake8#461]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

Code bit:
import os

Debug information:
Atom version: 1.14.3
Flake8 version: `3.0.4 (pyflakes: 1.5.0, pycodestyle: 2.0.0, mccabe: 0.6.1) CPython 3.5.3 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
