### ISSUE TITLE
Formatting print lines with print(f"{foo}") returns E999

### ISSUE THREAD

**Issue by ReagentX** [AtomLinter/linter-flake8#462]
When you print using the following Python 3 method, this linter displays E999 (SyntaxError: invalid syntax) for the first instance in a file:

    eventID = 1234
    print(f"Failed for {eventID}")
    print(f"Failed for {eventID}")

![](https://i.imgur.com/2q4sX5P.png)

**Comment by Arcanemagus** [comment]
If I had to guess you are using the "wrong" `python` to launch `flake8` so it is running in Python v2 mode instead of Python v3. Make sure that `python` is v3 in the environment you _initially_ launch Atom from.

**Comment by ReagentX** [comment]
How can  I check this? I am able to run the Python 3 code fine, however, the linter does not work.

**Comment by Arcanemagus** [comment]
You can ensure that the correct Python version is being used by:

1. Close _all_ instances of Atom
2. From a terminal ensure that `python --version` shows the desired results
3. **From that terminal** launch Atom (`atom .`)

**Comment by peterbe** [comment]
I have the same problem. I have `flake8` installed with pipsi and it uses Python 3.6.1 on my OSX.
So if I run:
```
$ flake8 foo.py
```
...it does not explain. 
But in Atom I get the same as this issue mentions at the top. 

My `flake8` executable runs with the right Python.
```
▶ cat `which flake8` | head -n 1
#!/usr/local/opt/python3/bin/python3.6
```

I still have Python 2.7 as the default for `python`.
I.e. 
```
▶ python --version
Python 2.7.11
```

The default is just `flake8` which should be right. 
<img width="899" alt="screen shot 2017-07-10 at 1 41 52 pm" src="https://user-images.githubusercontent.com/26739/28031541-a24c7348-6575-11e7-8a42-d375b5d8eb31.png">
I haven't changed the default. 

So why does it run `python` to start `flake8`?

**Comment by Arcanemagus** [comment]
@peterbe If you follow the instructions posted in the post right above yours, does it work?

**Comment by peterbe** [comment]
> @peterbe If you follow the instructions posted in the post right above yours, does it work?

It did! I still have `python --version` yielding 2.7 but as my point above, it's not using python to start flake8, it starts flake8 directly. 
So it turns out I just needed to fully restart Atom. 

Close this issue?

**Comment by Arcanemagus** [comment]
Good to hear that, _any_ sort of "virtualenv like" setup unfortunately requires Atom to be launched from that environment to work, and some don't even work then as they rely on shell macros that don't exist in the execution context of how `flake8` is launched here.

Since @ReagentX hasn't responded, I'm assuming their issue was resolved and closing this. If you are still having problems @ReagentX please let us know!
