### ISSUE TITLE
Flake8 rule 'F821' reported an invalid point

### ISSUE THREAD

**Issue by gm2bv** [AtomLinter/linter-flake8#463]
Flake8 reported an invalid point for the rule `F821`, with the messge `undefined name 'year_month'`.

Debug information:
Atom version: 1.17.2
Flake8 version: `3.2.1 (mccabe: 0.5.3, pycodestyle: 2.2.0, pyflakes: 1.3.0) CPython 3.5.2 on Darwin`

**Comment by Arcanemagus** [comment]
Can you try updating your `flake8` version to the latest released? It's possible this is related to a unicode handling bug that _should_ be fixed in it.

If you are still seeing this on v3.3.0 of `flake8` please upload a file that reproduces this.

**Comment by gm2bv** [comment]
I updated flake8 into v3.3.0 and fixed this problem.

Thank you for your support.
