### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by ludwigschwardt** [AtomLinter/linter-flake8#464]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

This was on the very first line of the script which happens to be a hash-bang line:

```Python
#! /usr/bin/env python
```

Debug information:
Atom version: 1.17.2
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2, flake8-docstrings: 1.0.2, pydocstyle: 1.0.0) CPython 2.7.13 on Darwin`

**Comment by philip-sterne** [comment]
I'm getting this too

**Comment by ludwigschwardt** [comment]
I also got the "NaN:NaN". Although now the error is gone somehow and I cannot reproduce it, not even with a one-liner script...

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
