### ISSUE TITLE
How can I debug the currently active virtualenv?

### ISSUE THREAD

**Issue by santiagobasulto** [AtomLinter/linter-flake8#467]
I'm getting the following error:

```
main.js [sm]:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "site.py", line 4, in <module>
    from django.utils.text import slugify
ImportError: No module named django.utils.text
```

I have Django installed in my current env and I **THINK** it's properly set, but the error is troubling me:

![image](https://user-images.githubusercontent.com/872296/27587463-e0e7fd44-5b1a-11e7-9b39-7e34ad78da84.png)

Someone can help? How can I debug what's the currently active env?

**Comment by santiagobasulto** [comment]
I realized the order in which each venv was appearing might be a problem, so I changed it to: `/Users/santiagobasulto/.virtualenvs/$PROJECT_NAME/bin/flake8;/usr/local/bin/flake8`

**Comment by Arcanemagus** [comment]
Yes, the order matters. They are tried in order so the first one you want needs to be the first listed.

**Comment by santiagobasulto** [comment]
@Arcanemagus I'd like to reopen this again. I still have the same error:

![image](https://user-images.githubusercontent.com/872296/28321759-0ea7fae4-6ba2-11e7-8eea-bcc5d5eebb64.png)

`json` is a default module. My virtualenv is currently active and I have it properly listed in the configuration:

![image](https://user-images.githubusercontent.com/872296/28321791-29cedb26-6ba2-11e7-83d9-0a67fd9d7673.png)

The flake8 executable exists:

![image](https://user-images.githubusercontent.com/872296/28321975-c3377d86-6ba2-11e7-98b6-236f7d3049a2.png)
