### ISSUE TITLE
Flake8 just stopped working after simple package update 

### ISSUE THREAD

**Issue by ricardolira** [AtomLinter/linter-flake8#469]
**# Description**

Everything was working fine until I updated one of the packages I work with (Pyhton-indent). The, after that it just stopped working, giving me the error:

linter-flake8:: Flake8 threw an error related to:
sh: error importing function definition for `BASH_FUNC_module'

**## Steps to Reproduce**

    1. Insert double space on your code between lines or indent your code more than enough (just do any type of action flake8 would recognize as a miscoding)
    2. Wait

**Expected behavior:** Flake8 correction suggestions

**Actual behavior:** It crashes

**Reproduces how often:** 100%

**## Versions**

>atom --version

    Atom : 1.16.0
    

    python
    git
   

**## Additional Information**

**## Error output from failed install:**

linter-flake8:: Flake8 threw an error related to:
sh: error importing function definition for `BASH_FUNC_module'
Please check Atom's Console for more details

**Comment by Arcanemagus** [comment]
First of all your Atom version is a bit old, v1.18.0 is the current stable.

What `linter-*` packages do you have installed? This was a tricky issue to track down all the other times it was reported, but it actually _should_ be fixed now thanks to https://github.com/steelbrain/consistent-env/pull/40.

My guess (especially with the old Atom version) is that you still have an old version of `consistent-env` installed (it's a dependency of a dependency of a dependency of this package). If you uninstall all packages that use the `atom-linter` npm dependency and then re-install them this should fix itself.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
