### ISSUE TITLE
Max Line Length and E501

### ISSUE THREAD

**Issue by dkirkby** [AtomLinter/linter-flake8#47]
Is the "Max Line Length" config parameter supposed to be passed as `--max-line-length` to `flake8`?  If so, it isn't working for me with atom 1.0.0, linter 1.1.0 and linter-flake8 1.4.2.  Here are the relevant lines from my `config.cson`:
```
  linter: {}
  "linter-flake8":
    maxLineLength: 95
```
but I am getting E501 errors based on a max-line-length of 79, as shown in this screen capture:
![e501](https://cloud.githubusercontent.com/assets/185007/8421559/7628e1d6-1e85-11e5-92d4-72b6a647773c.png)

**Comment by badray** [comment]
`config.cson` is not supported at the moment, supported config filenames are specified in this line https://github.com/AtomLinter/linter-flake8/blob/master/lib/linter-flake8.coffee#L24 Please wait a while as I merge and release @pjuren patch which will support custom specified config filename.

**Comment by dkirkby** [comment]
Isn't `~/.atom/config.cson` the default location for package settings entered via the Settings tab?  I didn't do anything special to specify this filename, but its what the "Atom / Open Your Config" menu item shows me.

Looking at your list of currently supported config filenames, it looks like my project's linter-flake8 config is coming from tox.ini.  What should I add there to set the max line length?  I tried this, which didn't work:
```
[linter-flake8]
maxLineLength = 95
```

**Comment by badray** [comment]
Sorry I forgot that `config.cson` is atom default package settings file :). But you should use a graphical plugin settings editor which is in `Atom->Preferences->Packages->linter-flake8->Settings`.

`tox.ini` file is read by flake8 directly, not by the linter, so in your case it should look like this:
```
[flake8]
max-line-length = 95
```

See http://flake8.readthedocs.org/en/latest/config.html for reference.

Hope it helps!

**Comment by badray** [comment]
@dkirkby Any feedback?

**Comment by dkirkby** [comment]
I just updated and the new version is working nicely with the default configuration scheme in atom 1.0 - thanks!

**Comment by badray** [comment]
:+1:
