### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by mrnonz** [AtomLinter/linter-flake8#473]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

`import pprint
import subprocess`

Debug information:
Atom version: 1.18.0
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2, flake8-docstrings: 1.0.2, pydocstyle: 1.0.0) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
