### ISSUE TITLE
Flake8 crashed!

### ISSUE THREAD

**Issue by lpdmm0416** [AtomLinter/linter-flake8#474]
linter-flake8:: Flake8 threw an error related to:
���������ļ���
Please check Atom's Console for more details

**Comment by Arcanemagus** [comment]
Something is crashing `flake8` itself. There _should_ be more information in the console, unfortunately it looks like your system encoding is set in a way that Atom doesn't understand so I'm not sure how readable the output will be for you.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
