### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by orlra** [AtomLinter/linter-flake8#475]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: unexpected EOF while parsing`.

`
from email.mime.text import MIMEText
from smtplib import sendmail

def sendmail_alert(to, reason, ip, attachment):
    sendmail('ser', to, msg)
    try:
        msg = MIMEText(str(reason) + 'alert failed on: ' + ip, 'plain')
        msg['Subject'] = to
        # some SMTP servers will do this automatically, not all
        msg['From'] = 'ser'
        try:
            sendmail(sender, destination, msg.as_string())
        except Exception as e:
            sys.exit("mail failed; %s" % str(e))`

Debug information:
Atom version: 1.18.0
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 1.1.0, mccabe: 0.2.1) CPython 3.5.2 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
