### ISSUE TITLE
Subclasses of OSError being highlighted as not imported

### ISSUE THREAD

**Issue by chrizandr** [AtomLinter/linter-flake8#483]
The subclasses of OSError, which are imported by the interpreter during runtime in Python 3 is highlighted as `F821 - Undefined Name`. 

Here is a list of the errors:
[https://docs.python.org/3/library/exceptions.html#os-exceptions](https://docs.python.org/3/library/exceptions.html#os-exceptions)

Is it supposed to be like that? Most other errors that are imported by the interpreter are not highlighted.

**Comment by Arcanemagus** [comment]
Without code to reproduce this I can't say for sure, this _sounds_ like an issue that should be reported over on [flake8](https://gitlab.com/pycqa/flake8) though as this project is just a wrapper around that.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
