### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by razhangwei** [AtomLinter/linter-flake8#491]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.19.1
Flake8 version: `2.1.0 (pep8: 1.4.6, mccabe: 0.2.1, pyflakes: 0.7.3) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
