### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by De4dSTyx** [AtomLinter/linter-flake8#493]
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

`# -*- coding: utf-8 -*-`

Debug information:
Atom version: 1.19.3
Flake8 version: `3.4.1 (flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.12 on Windows`

**Comment by Arcanemagus** [comment]
@De4dSTyx, @mmaja, and @shirshendubhowmick:
Are any of you able to share a file that reproduces this bug?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
