### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by glbello** [AtomLinter/linter-flake8#495]
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (80 > 79 characters)`.

Debug information:
Atom version: 1.19.5
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`

**Comment by Arcanemagus** [comment]
Please follow https://github.com/PyCQA/pycodestyle/issues/704 for updates on when this will get fixed in `pycodestyle` (which `flake8` uses internally).

**Comment by Arcanemagus** [comment]
Duplicate of #471
