### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by dataewan** [AtomLinter/linter-flake8#498]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: EOF while scanning triple-quoted string literal`.

Debug information:
Atom version: 1.19.2
Flake8 version: `3.0.4 (pyflakes: 1.2.3, mccabe: 0.5.2, pycodestyle: 2.0.0) CPython 3.5.1 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
