### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by joedborg** [AtomLinter/linter-flake8#50]
Got this from Atom deprecation warning:

AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/home/jborg/.atom/packages/Linter/lib/main.coffee:57:8)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
```

**Comment by steelbrain** [comment]
@badray would you wanna take this one or do you want someone else to do it?

**Comment by badray** [comment]
@steelbrain Every pull requests are welcome :+1: So if someone have time to do it I would be welcome.

**Comment by steelbrain** [comment]
I think I'm gonna take this one

**Comment by badray** [comment]
@steelbrain Have fun! :)

**Comment by steelbrain** [comment]
I'm caught up in some other work, if you wanna take it, please do :)

**Comment by osscca** [comment]
+1

**Comment by epequeno** [comment]
:+1:

**Comment by mcandre** [comment]
+1

**Comment by jkw** [comment]
Same error but different rows in source files:
``
Object.activate - C:\Users\jkw\.atom\packages\linter\lib\main.coffee:51:8
Package.activateNow - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:243:19
<unknown> - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:224:30
Package.measure - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15
Package.activate - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:216:14
PackageManager.activatePackage - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:453:21
``

**Comment by jkw** [comment]
Got this after todays update:
AtomLinter legacy API has been removed. Please refer to the Linter docs to update and the latest API: https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API
Report Issue
Object.activate - C:\Users\jkw\.atom\packages\linter\lib\main.coffee:52:6
Package.activateNow - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:243:19
<unknown> - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:224:30
Package.measure - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15
Package.activate - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:216:14
PackageManager.activatePackage - C:\Users\jkw\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:453:21

**Comment by Arcanemagus** [comment]
This will be completely broken until https://github.com/AtomLinter/linter-flake8/pull/56 is reviewed/merged.
