### ISSUE TITLE
Linter not detecting project configuration file on Atom Beta (1.21.0-beta0)

### ISSUE THREAD

**Issue by nogurenn** [AtomLinter/linter-flake8#501]
I've verified that my linter settings has `setup.cfg` and other possible config files. It may be related to #454  I filed before. This occurred when I started using the beta. I have no issues with the LTS version aside from the referenced issue.

**Comment by Arcanemagus** [comment]
I'm marking this as fixed by #428 as I'm not entirely sure how it would have been working before that, and nothing in this package or Atom changed around the time this was filed to have changed anything related to it.
