### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point (Requested Point NaN NaN)

### ISSUE THREAD

**Issue by cameck** [AtomLinter/linter-flake8#504]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

```
# -*- coding: utf-8 -*-
```
Debug information:
Atom version: 1.20.1
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by cameck** [comment]
Yes, it is fixed now. Thank you!
