### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by bdunubold** [AtomLinter/linter-flake8#505]
Flake8 reported an invalid point for the rule `E999`, with the messge `IndentationError: expected an indented block`.

Debug information:
Atom version: 1.20.1
Flake8 version: `3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Darwin`

**Comment by Arcanemagus** [comment]
Hmmm, you're on a new enough version that you shouldn't be hitting the common `E9__` bug, are you able to share the file that triggered this?

**Comment by Arcanemagus** [comment]
@SerAlbi or @SharpBit are either of you able to share a file that triggers this on the current `flake8` version? The previous known way to trigger this was fixed back in `flake8` v3.2.1.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
