### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by rspeer** [AtomLinter/linter-flake8#511]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

This happens whenever I am typing at the end of the file, and have typed a function declaration followed by a colon, but haven't typed the function body yet. I know it's a syntax error, but it's one that seems to screw up the rest of linter-flake8, and it asks me to report it.

Minimal example:

```
def example():
```

Debug information:
Atom version: 1.20.0
Flake8 version: `2.6.2 (pycodestyle: 2.0.0, mccabe: 0.5.0, pyflakes: 1.2.3) CPython 3.5.3 on Linux`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
