### ISSUE TITLE
Flake8 Times out within Atom on OSX

### ISSUE THREAD

**Issue by MichaelrMentele** [AtomLinter/linter-flake8#516]
Flake8 works on my Linux box but not on OSX. Not sure what the deal is been looking through past resolved issues and it looks like similar issues have been fixed in the past. I wonder if there was a regression within Atom for mac?

![image](https://user-images.githubusercontent.com/9519712/31681258-90002ffa-b32b-11e7-9bbc-766a1be0dce1.png)

**Comment by MichaelrMentele** [comment]
```
"*":
  "autocomplete-python":
    useKite: false
  core:
    closeEmptyWindows: false
    disabledPackages: [
      "es6-javascript"
      "language-javascript"
      "python-jedi"
      "python-tools"
    ]
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      "desktop.ini"
      ".pyc"
    ]
    telemetryConsent: "limited"
  editor:
    scrollPastEnd: true
    showIndentGuide: true
    softWrap: true
  "exception-reporting":
    userId: "004fede8-3970-4524-bae3-bdebce19c679"
  "linter-flake8":
    executablePath: "/Users/mmentele/Applications/anaconda2/bin/flake8; $PROJECT/.venv/bin/flake8;"
    pycodestyleErrorsToWarnings: true
  "linter-ui-default": {}
  "python-autopep8":
    formatOnSave: true
  "tree-view":
    hideIgnoredNames: true
```

**Comment by MichaelrMentele** [comment]
FWIW config ^

Not sure what other information to post.

**Comment by Arcanemagus** [comment]
If you are using anything newer than v2.2.0 that would mean that `flake8` was running for _over five minutes_. If that's the case something else is wrong on your system that `flake8` is taking that long 😉.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
