### ISSUE TITLE
Flake 8 crashing in atom

### ISSUE THREAD

**Issue by BobEarlK** [AtomLinter/linter-flake8#518]
Disabling Flake8 as keep getting a notice of crashing related to comparison of str and ints.  I see several threads about this [elsewhere](https://github.com/AtomLinter/linter-flake8/issues/451), but closed by ArcaneMagus and troubleshooting suggestions did not fix the constant crashing messages.  Tried to uninstall/reinstall without success.  Thanks very much for taking a look!

**Comment by Arcanemagus** [comment]
You haven't posted any errors of your own, but assuming you are hitting a similar error to #451 (which actually has nothing to do with `TypeError: unorderable types: str() > int()`) the problem is that your locale setting isn't correct.

What troubleshooting steps have you tried?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
