### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by Mjaggi98** [AtomLinter/linter-flake8#519]
Flake8 reported an invalid point for the rule `E901`, with the message `SyntaxError: unexpected EOF while parsing`.

# This is a bit of code that produces the bug

example = {0: 1, 'a': b, b: 'a'}

print(example[0])
print(example['a'])
print(example[10]

Debug information:
Atom version: 1.21.2
Flake8 version: `2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, ProxyChecker: 0.0.1, hacking.core: 0.0.1, pyflakes: 0.8.1) CPython 3.6.3 on Windows`

**Comment by Mjaggi98** [comment]
I figured it out it's all my bad but I don't know why it asked me to post it onto GitHub.

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

It sent you here because the version of `flake8` you currently have installed has a bug causing it to report an invalid (non-existent) position for all `E9__` errors. 😉

**Comment by Mjaggi98** [comment]
Thx
