### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by xrr** [AtomLinter/linter-flake8#525]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.22.0
Flake8 version: `2.5.0 (pep8: 1.7.0, pyflakes: 1.0.0, pep257: 0.2.1.post1, mccabe: 0.3.1, naming: 0.3.3) CPython 2.7.11 on Windows`

**Comment by xrr** [comment]
The error is not very explicit and do not indicates which line is problematic.
However it seems that a single line like the one below triggers the error :
`x =`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by xrr** [comment]
Indeed, many thanks for the advice !

For the record, after flake8's update I faced below error, that was solved by also updating pep8-naming :
"OptionManager' object has no attribute 'config_options'"
