### ISSUE TITLE
Add the 'F' option to the Select Errors Documentation

### ISSUE THREAD

**Issue by mr-ubik** [AtomLinter/linter-flake8#528]
In the documentation it is said that E and W will give all the errors, however this does not comprehend the FLake8 specific errors, the options to convert them to Linter Errors does not work if the F is not inserted into the Select Errors field.

**Comment by mr-ubik** [comment]
https://github.com/AtomLinter/linter-flake8/pull/529

**Comment by Arcanemagus** [comment]
As commented over in #529, the default value in `flake8` is `E,F,W,C90`, the setting is only for _restricting_ that.
