### ISSUE TITLE
Flake8 not responding/working at all when installed Python 3.6.3

### ISSUE THREAD

**Issue by Arielle2017** [AtomLinter/linter-flake8#531]
I started flake8 installation journey when it was for the default version Python 2.7  - At least I had some errors when typing in Atom alerting Flake8 was not setup correctly,
```
Flake8 crashed: "linter-flake8:: Flake8 threw an error related to:
Failed to spawn command ` /Users/nikifong/Library/Python/2.7/lib/python/site-packages`. Make sure ` /Users/nikifong/Library/Python/2.7/lib/python/site-packages` is installed and on your PATH
Please check Atom's Console for more details
```

to
```
inter-flake8:: Flake8 threw an error related to:
spawn EACCES
Please check Atom's Console for more details
```
when I changed PATH.

but now I installed Python 3.6.3, so I tried to use this version instead. That is where my nightmare got even worse. Before the new version, `which python` command worked and it would say `Python 2.7` but now it became `command not find`. 

I did `pip3 install flake8` - it worked! I got back
```
Collecting flake8
  Using cached flake8-3.5.0-py2.py3-none-any.whl
Collecting pyflakes<1.7.0,>=1.5.0 (from flake8)
  Using cached pyflakes-1.6.0-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: pyflakes, mccabe, pycodestyle, flake8
Successfully installed flake8-3.5.0 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.6.0
```

But, `which flake8` did not work
```
-bash: which: command not found
```

"pip3 list --format=columns", I had this:
```
Package     Version
----------- -------
flake8      3.5.0  
mccabe      0.6.1  
pip         9.0.1  
pycodestyle 2.3.1  
pyflakes    1.6.0  
setuptools  28.8.0 
```

"python3 --version"
Python 3.6.3

I also tried to export PATH:
```sh
export PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}
```
Again, `command not find`
 
Was it not linked? I am super confused now. Please help!!!!!

**Comment by Arcanemagus** [comment]
The fact that you are getting `command not found` for _internal_ Bash functions means there is something _majorly_ wrong with your Bash shell, to the point where I'm not even sure where to start helping you to get that working.

I'm marking this as closed just because it has nothing to do with this package, if you have any questions though feel free to keep commenting and I'll try to help...

**Comment by gonzalocasas** [comment]
@Arcanemagus I think @Arielle2017 is right, I just bumped into the same issue, flake8 is present when installed on python 2.7, but when switching to 3.6, the executable file is not present where it should (and it has nothing to do with bash as you suggested). My installation of flake8 was triggered by `pip install -r requirements.txt` for a package I'm developing, I tried to manually reinstall but still the same, then I try manually uninstall, and reinstall the requirements.txt file, and this time it worked.
