### ISSUE TITLE
flake8 crashed

### ISSUE THREAD

**Issue by bramvana** [AtomLinter/linter-flake8#540]
![flake8crashed](https://user-images.githubusercontent.com/24454138/33524312-44f80784-d81b-11e7-9115-862fa2e76104.png)

**Comment by bramvana** [comment]
Installed Atom. Want to learn to code Python. Looked for instructions on how to set up coding environment:
First problem was following instruction:
This package is called linter-flake8 and it’s an interface to flake8. To install it, you need to run: $ pip install flake8 $ pip install flake8-docstrings $ apm install linter-flake8
Tried typing this in Atom, but no effect. Typing this in an editor, so why would it have an effect? So installed linter and flake8 through Atom's built-in package installer. Also installed Python 3.6.3. Figured I'd be good to go now.
However, typing up whatever bit in an Atom editor page immediately gives error in image. What to do next?

**Comment by bramvana** [comment]
It's fixed. Never heard of mentioned PATH after 22 years of using, installing, reinstalling, optimizing, tweaking to bits every incarnation Windows. 

Why doesn't Python add a new rule for itself inside the PATH, or installs itself within a directory already part of the PATH variable? None of this manually adding locations to a PATH variable should be the norm in 2017. Or is there a reason for that?

**Comment by Arcanemagus** [comment]
The Python installer gives you an option to add it to the PATH for you:
![image](https://user-images.githubusercontent.com/427137/33569910-0836d1d4-d8e0-11e7-8deb-b1b3314dc7aa.png)

Unfortunately for some reason it seems they default that to disabled, so it's likely you just missed enabling it yourself which means you would need to manually set that part up.

Glad you got it figured out!
