### ISSUE TITLE
Flake8 rule 'D101' reported an invalid point

### ISSUE THREAD

**Issue by caaespin** [AtomLinter/linter-flake8#547]
Flake8 reported an invalid point for the rule `D101`, with the messge `Missing docstring in public class`.

```
from abc import abstractmethod, ABCMeta
import json
import re
```

Debug information:
Atom version: 1.22.1
Flake8 version: `3.5.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.2 on Darwin`

**Comment by Arcanemagus** [comment]
Are you able to share the file in the state that shows this error? If not, can you create a minimal reproduction case that you _can_ share?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
