### ISSUE TITLE
Flake8 rule 'F405' reported an invalid point

### ISSUE THREAD

**Issue by NCpySoft** [AtomLinter/linter-flake8#548]
Flake8 reported an invalid point for the rule `F405`, with the messge `'E' may be undefined, or defined from star imports: tkinter`.

Debug information:
Atom version: 1.22.1
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.4.4 on Windows`

**Comment by Arcanemagus** [comment]
Are you able to share a file/project that reproduces this so it can be filed against `flake8`?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
