### ISSUE TITLE
Flake8 rule 'E228' reported an invalid point

### ISSUE THREAD

**Issue by MarcusTiger** [AtomLinter/linter-flake8#550]
Flake8 reported an invalid point for the rule `E228`, with the messge `missing whitespace around modulo operator`.

Debug information:
Atom version: 1.23.1
Flake8 version: `3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.6 on Windows`

**Comment by Arcanemagus** [comment]
Are you able to provide a file to reproduce this with?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
