### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by barlaensdoonn** [AtomLinter/linter-flake8#553]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

line that caused this issue:
```
#!/usr/local/bin/python3
```

Debug information:
Atom version: 1.23.1
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.4.0, pyflakes: 1.0.0, flake8-docstrings: 0.2.6, pep257: 0.7.0) CPython 3.5.1 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
