### ISSUE TITLE
Settings max line length ignored

### ISSUE THREAD

**Issue by silentsokolov** [AtomLinter/linter-flake8#555]
I set `max line length` to 140 (or more), but I'm getting error E501

![1](https://user-images.githubusercontent.com/398939/34094148-00335888-e3dd-11e7-98c9-ff3a1b989961.jpg)
![2](https://user-images.githubusercontent.com/398939/34094149-004f0092-e3dd-11e7-9294-382bc43e2d1a.jpg)

python 2.7.11
flake8-3.5.0 pyflakes-1.6.0

Atom 1.23.1
linter-flake8-2.3.0

**Comment by silentsokolov** [comment]
Yes, sorry)

**Comment by Arcanemagus** [comment]
No problem, glad it was a simple fix 😉.
