### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by marcvanolmen** [AtomLinter/linter-flake8#560]
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

This crashes flake: ( according to the Atom.app)
```
    def sql_search_for_product_code(self, value):
        return u"""tst  {item_type} s metavalue2
        """.format(item_type=ItemProductType value=value)
```
When i add the missing comma then no flake crashes

```
    def sql_search_for_product_code(self, value):
        return u"""tst  {item_type} s metavalue2
        """.format(item_type=ItemProductType, value=value)
```

Debug information:
Atom version: 1.23.1
Flake8 version: `3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
