### ISSUE TITLE
Flake8 rule 'E502' reported an invalid point

### ISSUE THREAD

**Issue by dibrovsd** [AtomLinter/linter-flake8#568]
Flake8 reported an invalid point for the rule `E502`, with the messge `the backslash is redundant between brackets`.

Debug information:
Atom version: 1.23.3
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Darwin`

**Comment by ddaanet** [comment]
Invalid points are bugs in the linting tool, and should be reported upstream. 

https://gitlab.com/pycqa/flake8/issues

Besides, backslash _is_ redundant between brackets, you should probably fix your code ;-)

**Comment by Arcanemagus** [comment]
If you don't feel like tracking this down and filing it yourself @dibrovsd please upload a file that shows this and we can trace it down and file the issue 😉.

**Comment by dibrovsd** [comment]
Error not repeat :-(
Close issue
