### ISSUE TITLE
Error: ~/.config/flake8 ignored by linter-flake8

### ISSUE THREAD

**Issue by mcandre** [AtomLinter/linter-flake8#57]
By default, command line flake8 checks for configuration in places such as `~/.config/flake8`. However, linter-flake8 fails to load this configuration file by default, resulting in a surprising experience for newbies: linter-flake8 appears to ignore their preferred style settings.

Please check for flake8 configuration in `~/.config/flake8` by default, in addition to any Atom user specified locations.

**Comment by Arcanemagus** [comment]
This may be fixed in #77, or potentially a re-write of that. Will need testing.

**Comment by Arcanemagus** [comment]
@mcandre can you please test v1.8.0 (or higher) and see if this is working for you? Alternatively you might want to look into putting a `tox.ini` or `setup.cfg` file at the project level so the settings move with your project.

**Comment by Arcanemagus** [comment]
Any updates @mcandre?

**Comment by Arcanemagus** [comment]
Closing since there has been no input from @mcandre, if this is still an issue please re-open.

**Comment by elfkuzco** [comment]
`linter-flake8` is still not looking for system wide configuration files but rather for project configuration files. It would be great to have this as the default behaviour just like the `flake8` package specifies and still maintain support for project-level configurations.
