### ISSUE TITLE
[Linter] Error running Flake8

### ISSUE THREAD

**Issue by JayML669** [AtomLinter/linter-flake8#571]
Before posting this I found 2 posts on the same topic neither of which helped me:
#372 and #403 
After installing the linter-flake8 package on atom any time that I make any edit to a file I get the error

> [Linter] Error running Flake8
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

Upon opening the console I find the error:

> [Linter] Error running Flake8 Error: c:\python\python37\lib\site-packages\pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (C:\Users\MyUserName\.atom\packages\linter-flow\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Also using which flake8 returns the proper directory so I do have the python package installed. 
Thanks for any help!

**Comment by Arcanemagus** [comment]
This error is coming from the `stderr` output of Flake8:
```
Error: c:\python\python37\lib\site-packages\pycodestyle.py:113: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```

It looks like the version of `pycodestyle` embedded by `flake8` has an issue with that code. I would recommend double checking that it does/doesn't work with `pycodestyle` directly and filing an issue there if it has an issue.

**Comment by Arcanemagus** [comment]
It looks like https://github.com/PyCQA/pycodestyle/issues/728 is the bug to follow as the issue is in the `pycodestyle` code.

**Comment by georgelzh** [comment]
I have the same problem too :(

**Comment by RawrBear** [comment]
Same for me..

**Comment by AtsushiSakai** [comment]
same ...

**Comment by mikecheckyaself** [comment]
I think I had found a workaround in this post: https://github.com/PyCQA/pycodestyle/issues/728 
Basically you need change a line in the pycodestyle.py file in your python directory (I found it in Local/programs/python/python37-32/lib/site-packages) .

FIND: EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]') 
Change to: EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[\[({] | [\]}),;:]')

**Comment by Arcanemagus** [comment]
Locking this issue as it has nothing to do with `linter-flake8`. As already stated please follow https://github.com/PyCQA/pycodestyle/issues/728 for updates.
