### ISSUE TITLE
Error running flake 8

### ISSUE THREAD

**Issue by Techkillax** [AtomLinter/linter-flake8#574]
Hi, without changing anything (intentionally at least) I have an error when opening Atom: 

```
[Linter] Error running Flake8 Error: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pep8.py:102: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (/Users/xxxxx/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Studying previous posts didn't help, so I'm posting my own issue.

**Comment by Arcanemagus** [comment]
This is error text coming from `flake8`'s `stderr` stream, in this case it looks like the internal `pep8` has an error, or maybe is throwing an error related to your code.

What happens if you run `flake8` on the file manually?

**Comment by Techkillax** [comment]
I get something like this:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pep8.py:102: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
single_neuron.py:3:1: H306  imports not in alphabetical order (pandas, matplotlib.pyplot)
single_neuron.py:15:1: H404  multi line docstring should start without a leading new line
single_neuron.py:15:1: H405  multi line docstring summary not separated with an empty line
single_neuron.py:28:1: H404  multi line docstring should start without a leading new line
single_neuron.py:28:1: H405  multi line docstring summary not separated with an empty line

**Comment by Arcanemagus** [comment]
That's what I thought, you'll need to figure out why `flake8` is giving you errors. It looks like https://github.com/PyCQA/pycodestyle/issues/728 is what you want to follow as that is where the error is coming from.

Note that this might just be an issue in Python 3.7 as I don't see this on Python 3.6.3.

**Comment by cclauss** [comment]
Why is this issue closed?

Upgrading to production Python 3.7.0 on Mac OSX disables the current version of AtomLinter/linter-flake8 (with an error message every time I type a character) and I see no workaround in this issue?

**Comment by declantraynor** [comment]
@cclauss See my comment [here](https://github.com/PyCQA/pycodestyle/issues/728#issuecomment-402683613) for a temporary workaround.
