### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by abhyaasa** [AtomLinter/linter-flake8#585]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.25.1
Flake8 version: `2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1, pep257: 0.2.1.post1) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
