### ISSUE TITLE
ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator' 

### ISSUE THREAD

**Issue by cbrnr** [AtomLinter/linter-flake8#587]
All of a sudden I keep getting a flake8-related error when using Atom and the corresponding linter plugin. Apparently `pycodestyle` was updated to version 2.4.0 at some point, and now doesn't have the attribute `break_around_binary_operator` anymore. Is there anything that can be fixed in this plugin, or is the source of the problem somewhere else?

**Comment by Arcanemagus** [comment]
It sounds like that error is coming from `flake8` itself, are you able to run it from the CLI?

This provider is basically just a thin wrapper around running that for you.

**Comment by cbrnr** [comment]
You are right, thanks! This is a flake8 issue, which is already reported [here](https://gitlab.com/pycqa/flake8/issues/406) and [here](https://gitlab.com/pycqa/flake8/issues/415).
