### ISSUE TITLE
Unable to run flake from Windows Substystem for Linux

### ISSUE THREAD

**Issue by farin** [AtomLinter/linter-flake8#601]
I am running native Atom and whole Python environment is using WSL (with Ubuntu 18.04)
I don't want to install another python to Windows just for linter (with many more disadvantages like maintaining two independent versions)

I can easily run flake8 from windows command prompt using
`bash -c /usr/local/bin/flake8`
but command with arguments can be used in linter-flake8 settings

Similar to issue #515

**Comment by Arcanemagus** [comment]
As you pointed out this is essentially the exact same as #515: There are a myriad of ways you can proxy your execution of `flake8` and all of them have different workarounds. If you _really_ need to keep it in that other environment create a wrapper script in your native Windows install that works as a proxy.
