### ISSUE TITLE
Not work with tree-sitter

### ISSUE THREAD

**Issue by silentsokolov** [AtomLinter/linter-flake8#604]
Without tree-sitter:

![1](https://user-images.githubusercontent.com/398939/40111966-2b3c8068-590d-11e8-9653-91e4588d4898.jpg)

With tree-sitter:

![2](https://user-images.githubusercontent.com/398939/40111931-117e4ef4-590d-11e8-949c-e2c600189fa1.jpg)

Atom: 1.27.0 x64
Electron: 1.7.11
OS: Mac OS

Testing with safe mode

**Comment by bryanwweber** [comment]
The specific change that is made is the scope is changed from `source.python` to just `python`. The output from Linter: Debug with Tree-Sitter enabled:

```
Platform: darwin
Atom Version: 1.27.2
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
Disabled Linter Providers: 
Standard Linter Providers: 
  - Flake8
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - python
  - module
  - class_definition
```

and with tree-sitter disabled:

```
Platform: darwin
Atom Version: 1.27.2
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - Flake8
Disabled Linter Providers: 
Standard Linter Providers: 
  - Flake8
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.python
```

**Comment by Arcanemagus** [comment]
The root scope change was reverted before Tree-sitter was taken out of beta, closing.
