### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by barlaensdoonn** [AtomLinter/linter-flake8#605]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

Debug information:
Atom version: 1.27.1
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.4.0, pyflakes: 1.0.0, flake8-docstrings: 0.2.6, pep257: 0.7.0) CPython 3.5.1 on Darwin`

**Comment by barlaensdoonn** [comment]
the docstring in this function caused this. probably my fault for using strings in the docstring, but I'll leave it open for now in case it's useful

`def initialize_client(config, env='prod'):
    '''env can be either 'test' or 'prod', but we'll only ever use 'prod''''

    caas_client = client.EntityServiceClient('prod')
    caas_client.x_api_key = config['CAAS_API_PROD_KEY']  # specify our API key for the client

    return caas_client`

**Comment by barlaensdoonn** [comment]
the docstring in this function caused this. probably my fault for using strings in the docstring, but I'll leave it open for now in case it's useful

`
def initialize_client(config, env='prod'):
    '''env can be either 'test' or 'prod', but we'll only ever use 'prod''''

    caas_client = client.EntityServiceClient('prod')
    caas_client.x_api_key = config['CAAS_API_PROD_KEY']  # specify our API key for the client

    return caas_client
`

**Comment by barlaensdoonn** [comment]
this was my fault for using a 'string' at the very end of a '''docstring'''. i can't even paste the code as an example since github also doesn't recognize it as valid. here's an example:

'''keyword env can be either 'test' or 'prod', be we'll only ever use 'prod''''

changing the triple single quotes to triple double quotes (''' -> """) gets rid of the error

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
