### ISSUE TITLE
"Max Line Length" ignored

### ISSUE THREAD

**Issue by tobiasfielitz** [AtomLinter/linter-flake8#606]
Have restarted Atom, disabled/enabled `linter-flake8`, no success.
v2.3.0

![screen shot 2018-05-24 at 9 48 34 am](https://user-images.githubusercontent.com/9712861/40457137-2d2cf502-5f38-11e8-93cf-a897751e0abd.png)
![screen shot 2018-05-24 at 9 48 49 am](https://user-images.githubusercontent.com/9712861/40457138-2d802b8c-5f38-11e8-8602-6bc73990313c.png)

Let me know if you need any additional info.

**Comment by alextucker** [comment]
@tobiasfielitz Do you have a `setup.cfg`, `tox.ini`, or `.flake8` in your project? It appears that those files will override the settings that you set in Atom preferences.

**Comment by alextucker** [comment]
@tobiasfielitz Given my understanding of how `flake8` itself works, there is little `linter-flake8` can do to override this behaviour (or merge config files). I would suggest just closing this issue yourself.
