### ISSUE TITLE
Why is lintOnFly disabled?

### ISSUE THREAD

**Issue by code-tree** [AtomLinter/linter-flake8#61]
Just wondering the reasoning behind disabling lintOnFly, as it seems like it would be better to inherit Linter's setting?

Was it found to make Atom too slow?

**Comment by badray** [comment]
@code-tree I've been experiencing to much cpu-consuming Atom :), but that was with early versions of editor/Linter, maybe now it will be working fine. 

Do you think we should inherit Linter's default settings?

**Comment by Arcanemagus** [comment]
It's executing async, so it shouldn't be a huge UI hit to enable lintOnFly for those that use it.

**Comment by code-tree** [comment]
Yes, I think it is probably better to follow the user's main Linter config. I overrided linter-flake8's setting and it seems to work fine (I'm running a mid-range modern laptop).

**Comment by arielpontes** [comment]
I'm trying to get `linter-flake8` to throw errors/warnings as I type (like in the demo gif) but it won't work. I was going to create an issue but I found this one. Is it possible to turn lintOnFly on somehow? It's already ticked on the Linter settings but there's no effect. According to the demo .gif it should be possible somehow, but I don't know how to do it.

**Comment by code-tree** [comment]
The solution at the moment is to simply edit the code. There is basically only one file for this plugin, so shouldn't be hard to find. Look for "lintOnFly".

**Comment by arielpontes** [comment]
Thanks. I realized later that this was probably the only solution. It did the trick. I also agree it should inherit the Linter's setting (or at least be independently configurable).

**Comment by Ryex** [comment]
setting the line to true works for me and I'm heaving no noticeable performance hit even on files > 10K lines.

it should inherit the main linter settings. if your worried about it add a local setting to lint on the fly so the user can choose.
