### ISSUE TITLE
Atom linter-flake8 failed to spawn (not in PATH)

### ISSUE THREAD

**Issue by metaclay** [AtomLinter/linter-flake8#610]
i installed linter-flake8 package in Atom . I got this error : 

> [Linter] Error running Flake8 Error: Failed to spawn command `flake8`. Make sure `flake8` is installed and on your PATH

i'm sure flake8 is in the PATH . Have a look at the image i attach. I try to input the executable path to the flake8 setting but still doesn't work. I use windows 10 and i have python 2.7 and 3.5 installed . Does anyone know the solution ?

![image 054](https://user-images.githubusercontent.com/21150330/40871798-d4e8817c-666c-11e8-8bd3-eb0baa088d45.png)

![image 048](https://user-images.githubusercontent.com/21150330/40871789-b9393d86-666c-11e8-8446-08b105a9f864.png)
![image 049](https://user-images.githubusercontent.com/21150330/40871793-be2fb63a-666c-11e8-9d73-bb6f97d1168b.png)
![image 047](https://user-images.githubusercontent.com/21150330/40871800-e0146fe8-666c-11e8-8e9c-a353f076fed3.png)
![image 050](https://user-images.githubusercontent.com/21150330/40871803-e2e7d91c-666c-11e8-87b1-46b6abe31863.png)
![image 052](https://user-images.githubusercontent.com/21150330/40871806-ebba2220-666c-11e8-970b-a99fb632ec76.png)

**Comment by Arcanemagus** [comment]
The fact that Python is able to import the `flake8` _module_ doesn't mean that you have a properly installed `flake8` _executable_. Make sure that `flake8 --version` works from the command prompt, then launch Atom from that environment (and remove your executable path overrides).
