### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by vamsi1994** [AtomLinter/linter-flake8#611]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.27.2
Flake8 version: `2.6.2 (pycodestyle: 2.4.0, mccabe: 0.5.3, pyflakes: 1.2.3) CPython 2.7.15 on Windows`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
