### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by tqa236** [AtomLinter/linter-flake8#612]
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

#!/usr/bin/env python

Debug information:
Atom version: 1.26.1
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0, radon: 2.0.2) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment]
Duplicate of #628
