### ISSUE TITLE
linting cython files

### ISSUE THREAD

**Issue by ramezquitao** [AtomLinter/linter-flake8#616]
As far as my test go, flake is only testing .py files. Is it possible to make it check .pyx and .pxd files?

I'm using the following setup file but it is not working:

################################
[flake8]
filename = *.pyx,*.px*
exclude = .eggs,*.egg,build
ignore = E901,E999,E225,E226,E227
 ################################

Thanks

**Comment by Arcanemagus** [comment]
This package lints _anything_ Atom considers to be Python code, regardless of what the file extension is. If you want to customize how Atom recognizes a file's language see [Customizing Language Recognition](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).
