### ISSUE TITLE
Linter-Flake8 error

### ISSUE THREAD

**Issue by seelos** [AtomLinter/linter-flake8#620]
New to Python/programming - trying to set up an environment to learn/practice. I can't get flake8 to work. I keep receiving an error that I believe is stating flake8 is not in the correct path? (see image) I tried changing the path setting in linter-flake8 to match where my Command Prompt is showing flake8 (see other image) was installed, but no luck. Not sure if I'm doing it right. 

Thanks for your help.

![flake8 installed](https://user-images.githubusercontent.com/41172581/42664817-cc5d5efc-860a-11e8-9ae2-e00dc975bafa.PNG)
![flake8 error in atom](https://user-images.githubusercontent.com/41172581/42664818-cc68ef74-860a-11e8-8e93-5b82f27b0c67.PNG)

**Comment by Arcanemagus** [comment]
Assuming Python was installed normally you _may_ just need to fully restart Atom if you haven't since installing Python.

Does `where.exe flake8` show a result?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
