### ISSUE TITLE
Error when running on python 3.7

### ISSUE THREAD

**Issue by tadeoos** [AtomLinter/linter-flake8#621]
Hey, homebrew upgraded my python to 3.7 and since the linter stopped woking, spitting out this error:
```
[Linter] Error running Flake8 Error: /usr/local/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (/Users/Tadeo/.atom/packages/linter-eslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```
When I run flake8 manually in project it gives the same message as a warning and then runs normally

**Comment by Arcanemagus** [comment]
See https://github.com/PyCQA/pycodestyle/issues/728.

**Comment by didam** [comment]
SEE => https://www.scivision.co/python37-extraneous-whitespace-regex-pycodestyle-fix/

**Comment by didam** [comment]
SEE below, as given by:  https://www.scivision.co/python37-extraneous-whitespace-regex-pycodestyle-fix/

Workaround:
A workaround for this issue is to edit ~/miniconda3/lib/python3.7/site-packages/pycodestyle.py, replacing

# EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[\[({] | [\]}),;:]')

**Comment by scivision** [comment]
Thanks @didam the new line is
```python
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[\[({] | [\]}),;:]')
```

**Comment by jscottcronin** [comment]
for Python 3.7.2 (both Anaconda version and brew installed version) with:
* pep8==1.7.1
* pycodestyle==2.4.0

Update this line:
```python
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[\[({] | [\]}),;:]')
```
in *BOTH*:
lib/python3.7/site-packages/pycodestyle.py
lib/python3.7/site-packages/pep8.py

**Comment by cmfcruz** [comment]
I resolved this by reinstalling flake8.

`pip3 install --force flake8`

Upgrading to the latest version might also help for others.

`pip3 install --upgrade flake8`
