### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by iernstig** [AtomLinter/linter-flake8#627]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

The code which produced the error seems to be: 
from kivy.app import App

Debug information:
Atom version: 1.29.0
Flake8 version: `2.6.2 (pycodestyle: 2.0.0, mccabe: 0.5.3, pyflakes: 1.2.3) CPython 3.6.6 on Darwin`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
