### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by Invisible786** [AtomLinter/linter-flake8#629]
Flake8` reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

`mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`
`for num in mylist:`
`    if num % 2 == 0:`
 `       print(num)`
`    else:`
`        print(f'odd number {num}')
`

Debug information:
Atom version: 1.29.0
Flake8 version: `2.6.2 (pycodestyle: 2.4.0, mccabe: 0.5.3, pyflakes: 1.2.3) CPython 3.6.5 on Windows`

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.
