### ISSUE TITLE
Remove executableDir setting

### ISSUE THREAD

**Issue by badray** [AtomLinter/linter-flake8#63]
Variable isnt used anymore in `1.6.0` and it just confuses users.

**Comment by WilliamMayor** [comment]
If anyone is having problems after updating the plugin with an error about not being able to spawn flake8. I had to put the full path to my flake8 binary (`/usr/local/bin/flake8`) in the "Executable Path" setting, ignoring the "Executable Dir" setting.

**Comment by michaelaye** [comment]
yes, having that problem, but if I were to put the executable path in there, then I cannot switch between python2 and python3 flake anymore by just having it picked up from the PATH?

**Comment by Arcanemagus** [comment]
@michaelaye it _should_ grab it from the environment if you don't specify anything in the `Executable Path` setting at all. Unfortunately this doesn't work in several instances currently, so the setting allows you to force its location.

So try having nothing configured there and see if it grabs the one from your environment.

**Comment by michaelaye** [comment]
I don't, getting big No Spawn error then.

**Comment by Arcanemagus** [comment]
Marking this as closed, it is no longer relevant after the re-write.
