### ISSUE TITLE
How can i configure the linter-flake8 on windows10？

### ISSUE THREAD

**Issue by lockbro** [AtomLinter/linter-flake8#632]
I have already installed flake8 with Anaconda,and i also put the Script floder in $PATH,but it just cant't show the erro icon when i code the erro code,so please tell how to configure this plugin on Windows.

**Comment by Arcanemagus** [comment]
@DLI1996 You are hitting https://github.com/PyCQA/pycodestyle/issues/728.

@lockbro I'm going to close this since you haven't responded to the above questions. If you are still having issues feel free to update this, thanks!
