### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by user321name** [AtomLinter/linter-flake8#636]
NOT WORKING FOR ME, NO RED MISTAKE SIGN

**Comment by Arcanemagus** [comment]
FYI, the caps lock key is on the left hand side of your keyboard, yours seems to have been enabled before you posted this 😉.

"Not working" doesn't really give me anything to go on. Do you have `flake8` installed on your computer? Do you have `linter` or `atom-ide-ui` installed and enabled? Are you getting any error messages?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
