### ISSUE TITLE
Allow for linting on save, rather than on typing

### ISSUE THREAD

**Issue by gappleto97** [AtomLinter/linter-flake8#638]
Several other linter projects have this, and it is very nice to not have 40% CPU usage just because I am typing.

For an example on how this is implemented, see linter-mypy

**Comment by gappleto97** [comment]
Turns out this is in the settings for linter. I think this is somewhat confusing, since other linter projects have it in their main setting, but this is not a necessary feature to implement as long as there is a note about it in the settings page.

**Comment by Arcanemagus** [comment]
This is just a provider of a wrapper for `flake8`, it's up to the caller (`linter` or `atom-ide-ui` to determine when and how often it gets called).
