### ISSUE TITLE
Clashes with autopep8

### ISSUE THREAD

**Issue by michaelaye** [AtomLinter/linter-flake8#64]
I work with autopep8 activated on save and because it takes some time for any issues to be repaired, these pop us as flake8 probs as well even so they are being fixed at the exact moment, flake8 complains about them.
So, could we either (or both) have a delay on the 'check on save' action for flake8, or/and an option where I could perform the check only on command not at every save?

**Comment by Arcanemagus** [comment]
Simply disable `Lint On Save` in the settings of the main `linter` package. `linter-flake8` has no control over when it is ran, it only provides a service that is consumed by the `linter` package.
![image](https://cloud.githubusercontent.com/assets/427137/9215924/3d3536a6-4066-11e5-919e-f5eb23b84203.png)

If you also have Lint on fly disabled you would then need to manually trigger the lint from your command palette.

**Comment by michaelaye** [comment]
I don't see a Lint On Save in the main linter package? Do you mean `Lint on Fly` ?

![screenshot 2015-08-12 11 42 24](https://cloud.githubusercontent.com/assets/69774/9231777/41c03082-40e7-11e5-8bb8-9023d1375fff.png)

**Comment by steelbrain** [comment]
@michaelaye You need to contact author of that repo and tell them to set `modifiesBuffer:true` on the linter object, that way their linter will no longer conflict with any other packages and will be run before anything else, it will also be run in series instead of parallel to avoid those race-conditioned-buffer-modification scenarios.

**Comment by michaelaye** [comment]
but the clash only exists because this package decides to do linting on-save, despite not being supported by the linter package? So, by definition of the linter-package, this should never occur.

**Comment by steelbrain** [comment]
@michaelaye We have two types of linter, those who modify buffers and those who don't, the package you mentioned modifies buffer and it will conflict with packages unless it sets those param in it's linter object.

**Comment by michaelaye** [comment]
ah, I did not realize that you talk about the autopep8 package, did not understand that as a linter, thanks.

**Comment by Arcanemagus** [comment]
@steelbrain I don't think he is using a linter package, I'm guessing either https://github.com/markbaas/atom-python-autopep8 or the support built into AtomBeautify?

**Comment by steelbrain** [comment]
@Arcanemagus He should, if that package author wants to avoid conflicts with linters. 'cause there's no other way :)

**Comment by michaelaye** [comment]
I'm using the former, python-autopep8

**Comment by Arcanemagus** [comment]
As @steelbrain said, there really isn't a way to avoid a conflict here as the packages have no idea what the other is doing. Your only solution @michaelaye would be to make _one_ of the packages only do stuff when you ask it to. I would think that autopep8 would be the ideal candidate for that myself, but I guess that would be a personal preference.

Unfortunately it looks like currently the `linter` package will always trigger a lint on the save event so you can't avoid that in any case. Unless I'm mistaken @steelbrain?

**Comment by steelbrain** [comment]
@Arcanemagus You are right, it always tries to lint on save (unless there's a previous lint operation in progress)

**Comment by Arcanemagus** [comment]
So @michaelaye the simplest thing would be to trigger the `autopep8` run manually, it looks like `Ctrl+Alt+S` is the default keybinding for that in the package.
