### ISSUE TITLE
Issue with installing flake8

### ISSUE THREAD

**Issue by andretwx** [AtomLinter/linter-flake8#642]
[error.txt](https://github.com/AtomLinter/linter-flake8/files/2455031/error.txt)

I've just started learning so I'm not sure how to properly install flake8. What I've done so far are installing flake8 and setting its path, however I am still getting this error while in atom. Can someone give their advice?

**Comment by Arcanemagus** [comment]
It looks like you manually installed `pycodestyle`, and the version you have installed isn't compatible with the version of `flake8` that you have installed. You'll need to resolve that first before you can try using it in Atom through `linter-flake8`.
