### ISSUE TITLE
configFileNames is completely ignored

### ISSUE THREAD

**Issue by caktux** [AtomLinter/linter-flake8#66]
Seems it wasn't re-implemented in the 1.5.0 to 1.6.0 upgrade...

**Comment by badray** [comment]
Will be fixed in 1.6.1

**Comment by gbrassey** [comment]
This wasn't fixed in 1.6.1. Any idea when it will be addressed @badray? Thanks

**Comment by Arcanemagus** [comment]
v1.6.1 was released a bit early, @badray will probably be implementing this in the next version.

**Comment by sgtsquiggs** [comment]
So we're waiting on 1.6.2 for this?

**Comment by Arcanemagus** [comment]
This has already been implemented in #68, we're just waiting on @badray.

**Comment by paltman** [comment]
Would love a release. :+1:

**Comment by Arcanemagus** [comment]
@badray it's been almost a month and a half since you last reviewed anything here, do you need any any help working on this?

**Comment by Arcanemagus** [comment]
This was just released in v1.7.0, you can close this now (after testing of course :wink:).

**Comment by sgtsquiggs** [comment]
Working when setting `Profile Config File` to tox.ini, etc. What is the difference now between `Project Config File` and `Config File Names`? How is `Config File Names` used?

**Comment by Arcanemagus** [comment]
@sgtsquiggs The main difference? `configFileNames` doesn't exist :stuck_out_tongue:.

`configFileNames` is an older setting that is no longer used. Unfortunately Atom likes to display anything that is in the config file, regardless of whether the package actually specifies them.

`projectConfigFile` is the only currently used configuration file.

**Comment by sgtsquiggs** [comment]
Got it!

**Comment by paltman** [comment]
It is still ignoring my `tox.ini` file.

**Comment by paltman** [comment]
I don't see a `Project Config File` setting though.

<img width="747" alt="screen shot 2015-10-03 at 6 35 39 am" src="https://cloud.githubusercontent.com/assets/1192/10262710/0a5d3420-6999-11e5-868a-db15428670d7.png">

**Comment by Arcanemagus** [comment]
Something isn't quite right with your install, it says that it is v1.7.0, but the descriptions are from before the re-write to update it to the new API.

It should look like this:
![image](https://cloud.githubusercontent.com/assets/427137/10289061/5714d156-6b51-11e5-80e5-2d29f60b6368.png)

Can you try uninstalling the package, removing the relevant sections from your `config.cson`, and then re-installing the package?

**Comment by paltman** [comment]
:+1: working great now

**Comment by Arcanemagus** [comment]
Marking this as closed since a version including this has been released.
