### ISSUE TITLE
[Linter] Error running Flake8 Error: Failed to spawn command `flake8`.

### ISSUE THREAD

**Issue by poojapatel10** [AtomLinter/linter-flake8#678]
linter-registry.js? [sm]:145 [Linter] Error running Flake8 Error: Failed to spawn command `flake8`. Make sure `flake8` is installed and on your PATH
    at /Users/xyz/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.js:130
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)

**Comment by poojapatel10** [comment]
Using macOS High Sierra
version 10.13.6
Atom version  1.34.0

**Comment by Hallohannes123** [comment]
I have the same issue

**Comment by Arcanemagus** [comment]
You need to have installed [`flake8`](https://pypi.org/project/flake8/) and either have it in your `PATH`, or specify the full path in the settings **before** attempting to use this package.
