### ISSUE TITLE
Instead of a setting for white listing error letters, change it to blacklisting error letters.

### ISSUE THREAD

**Issue by LeptoSpira** [AtomLinter/linter-flake8#688]
Let's say you want flake8 to flake everything but docstrings. you can't type D in the field, you have to type every single letter except D to do that. Please change it from whitelisting to blacklisting.

**Comment by Arcanemagus** [comment]
The "Select Errors" option is passed _directly_ to `flake8`'s `--select` option... the same as the "Ignore Error Codes" option is passed directly to `flake8`'s `--ignore` option. From [the documentation](https://flake8.readthedocs.io/en/latest/user/invocation.html) on those options it looks like they both operate in the same manner, so you could put `D` in the "Ignore Error Codes" option and it should work.

Note that these are both options that _override_ `flake8`'s configuration, it sounds like you might be better served by creating a configuration file for `flake8`, as described in [their documentation](https://flake8.readthedocs.io/en/latest/user/configuration.html).
