### ISSUE TITLE
How to STOP linter when editing file with particular extension?

### ISSUE THREAD

**Issue by 7sDream** [AtomLinter/linter-flake8#69]
When I editing a markdown file, with extension ".md"，I use a python code block in it, and then I found that linter-flake8 is running.

How can I STOP it in this file? 
Because wrnings and errors  about markdown file is neaningless and sometime interrupt my thinking.

![pic of warning and errors](https://cloud.githubusercontent.com/assets/7822577/9428593/2a6c47b0-49e6-11e5-9e52-a4149ca942bd.jpg)

**Comment by Arcanemagus** [comment]
I'm assuming this is similar to this issue: https://github.com/atom/language-gfm/issues/121

Can you file a new issue related to Python on that repo? (Or even better a PR for them to review :wink:)

To temporarily stop it from showing for that file run `Linter: Toggle` to disable linting the file for that editor session.

**Comment by Arcanemagus** [comment]
Marking this as closed as it isn't an issue with `linter-flake8`.
