### ISSUE TITLE
[Linter] Error running Flake8 Atom Mac

### ISSUE THREAD

**Issue by Jsanchez2263** [AtomLinter/linter-flake8#697]
Hello,

I am brand new to using Atom and learning Python. I tried following a video to configure Atom, and when I got to the linter-flake8 package, I ran into some issues. I've attached screenshots of my errors. If someone could give me a step-by-step walkthrough to fix this, that would be great. I've looked at many articles/forums and haven't found anything to resolve my issue. Any suggestions would be helpful. TIA!
<img width="482" alt="Screen Shot 2019-05-28 at 10 36 23 PM" src="https://user-images.githubusercontent.com/51138487/58527988-88b4ae80-819a-11e9-8666-4fb52cc6859e.png">
<img width="968" alt="Screen Shot 2019-05-28 at 10 36 37 PM" src="https://user-images.githubusercontent.com/51138487/58527995-8d796280-819a-11e9-91fd-7751abf0babc.png">

**Comment by Arcanemagus** [comment]
You need to either:
* Update `flake8` to 3.6.0 or later
* Downgrade to Python 3.6
