### ISSUE TITLE
Document usage of $PATH for {configuration, virtualenv package}-less virtualenv/flake8 setting

### ISSUE THREAD

**Issue by ronjouch** [AtomLinter/linter-flake8#71]
Hi, this is not really an "issue", more of a discussion of a nice hack I use that might deserve documentation. If you are interested, feedback welcome, and I can make a PR adding a paragraph at the end of `README.md`.

---

I love this package, but don't like very much having to go to Settings to set my flake8 each time I work on a Python 2 project.

→ Since I start Atom from the command-line anyway (`atom /path/to/project_folder/`, for which Atom will remember open files), rather than having to murk with Atom configuration, I set up:

* The usual virtualenv with my python2/python3/pypy choice for project A/B/C.
* A folder with a `flake8` symlink pointing to my non-default flake8 (in my case under Arch Linux, `ln -s /usr/bin/flake8-python2 ~/.flake8-python2/flake8`)

Then I can start an Atom session...

* ... for a python3 / stdlib-only project with `atom /path/to/vanilla_project/`
* ... for exotic projects by prepending a modification to `$PATH`. For example, I start an Atom session for my python2-based [dailygrooves](https://github.com/ronjouch/dailygrooves) with `PATH=~/.virtualenvs/dailygrooves/bin:~/.flake8-python2/:$PATH atom ~/projects/dailygrooves/`

Repeatable, stateless virtualenv/flake8 Atom environments! :tada: . Thoughts? I started the same discussion at https://github.com/sadovnychyi/autocomplete-python/issues/56

**Comment by ronjouch** [comment]
Update:

1. My desire to update `$PATH` to include my `/path/to/project_virtualenv/bin` was nonsense, that's what activating a virtualenv is for.
2. Remains autodedection for the flake8 version (Python 2 / 3). Here's a PR for that: https://github.com/AtomLinter/linter-flake8/pull/74

**Comment by Arcanemagus** [comment]
I _think_ this can be closed based on the earlier comments and what I remember of discussions in a related PR.

@ronjouch if you feel this should still be open please feel free to re-open this!
