### ISSUE TITLE
Irrelevant space warnings/errors in linter-flake8 and linter error

### ISSUE THREAD

**Issue by JordanTheDodger** [AtomLinter/linter-flake8#714]
E226, E231

using atom for  python 
I believe this is the reason for the lag. I used atom in safe mode, everything was working smooth as butter. 
The linter package sometimes take a while to check through your code. I had a warning message,idk if this is why the lag is happening. I am ataching a ss of the error. I am not that good with CSS, but I believe there is something wrong with CSS script. You get the error after you install the dependencies.`
![linter flake 8 problem](https://user-images.githubusercontent.com/54824287/67599862-f3184d80-f73e-11e9-9c4f-6a3962f2a522.PNG)
`

**Comment by juan1tovar** [comment]
Hi :)
I have this simple code and linter shows the E231 - missing whitespace after ',' error

mylist = [1,2,3]
print(mylist[10])

It runs perfectly.

My English is a work in progress...
