### ISSUE TITLE
[Linter] Error running Flake8

### ISSUE THREAD

**Issue by jackbomb88** [AtomLinter/linter-flake8#729]
I am new to python. Follow a YouTube Video set up Atom, however, when I started coding it keeps popping these error messages:

<img width="466" alt="1" src="https://user-images.githubusercontent.com/63440420/78965413-fd38d780-7b37-11ea-98bb-1a0af826bbc1.png">
<img width="759" alt="2" src="https://user-images.githubusercontent.com/63440420/78965421-03c74f00-7b38-11ea-9bde-56ee6ebaa5fd.png">

Python Version is 3.8.2, using a Mac laptop. I installed linter-flake8 in Atom and followed all instructions. 

Could someone please give me a step-by-step detailed instruction on how to fix it, please.
I really appreciate all y'all help!

**Comment by vepain** [comment]
Hi,

Could you tell us what is the output of commands:
- `which flake8` 
- `flake8 --version`

Have you installed flake8 for python3.8 with taking care of pip version ? 
*i.e.* using `python3.8 -m pip install flake8`? (to test if installed: `python3.8 -m flake8 --version`)

In the options of linter-flake8 atom package, there is the path of bin flake8 to add. You should put the absolute path or adding the path of bin directory containing it in your **.bashrc** or in your **.bash_aliases**

**Comment by arfelo1** [comment]
I have the same problem, but for a Windows 10 laptop.
When I write command 
- flake8 --version

I get this:

- 3.7.9 (flake8-docstrings: 1.5.0, pydocstyle: 5.0.2, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.2 on Windows

But when I write the command

- which flake8

It says that  

> 'which' is not recognized as an internal or external command,
operable program or batch file. 


EDIT:
I found the command 

- where.exe flake8
in another thread, but what it gives me is this:
INFO: Could not find files for the given pattern(s).

**Comment by vepain** [comment]
> But when I write the command
> 
>     which flake8
> 
> It says that
> 
>     'which' is not recognized as an internal or external command,
>     operable program or batch file.

Yes sorry, it was for bash language (Unix)

> where.exe flake8
>
> in another thread, but what it gives me is this:
> INFO: Could not find files for the given pattern(s).

While `flake8 --version` works, hum, I don't really know how this is possible (perhaps the flake8 file is not an executable, but a python script as on Unix so...)

But normally, if `flake8 --version` works, then it is in your **PATH** environment variable so get the absolute path of flake8 and give it to **linter-flake8** option `Executable Path`
https://www.shellhacks.com/windows-cmd-path-variable-add-to-path-echo-path/
(sorry, I'm not a windows programmer ^^)

Could you test just flake8 on an erroneous file for testing if it works properly first ? 

Do you use a virtual env ?

**Comment by vepain** [comment]
Too, verify your **python-language-server** version with `python3.8 -m pip freeze`

**Comment by arfelo1** [comment]
What I get doing this:
> But normally, if `flake8 --version` works, then it is in your **PATH** environment variable so get the absolute path of flake8 and give it to **linter-flake8** option `Executable Path`
> https://www.shellhacks.com/windows-cmd-path-variable-add-to-path-echo-path/
> (sorry, I'm not a windows programmer ^^)

Is this path: C:\Users\arfel\AppData\Local\atom\bin

But I had already put it in the Executable Path option and I am still getting the same error when I open any file.


With this:
> Too, verify your **python-language-server** version with `python3.8 -m pip freeze`

I get this info:
autopep8==1.5.1
entrypoints==0.3
flake8==3.7.9
flake8-docstrings==1.5.0
mccabe==0.6.1
pycodestyle==2.5.0
pydocstyle==5.0.2
pyflakes==2.1.1
snowballstemmer==2.0.0

**Comment by vepain** [comment]
> Is this path: C:\Users\arfel\AppData\Local\atom\bin

It is not the path of the directory containing the flake8 executable script, but this of atom :p 

> But I had already put it in the Executable Path option and I am still getting the same error when I open any file.

So normal

Have you just kept `flake8`  in **linter-flake8** option `Executable Path` ? 
I don't understand why `flake8 --version` in terminal (Powershell ?) works while **linter-flake8** can't find flake8.

> I get this info:
> autopep8==1.5.1
> entrypoints==0.3
> flake8==3.7.9
> flake8-docstrings==1.5.0
> mccabe==0.6.1
> pycodestyle==2.5.0
> pydocstyle==5.0.2
> pyflakes==2.1.1
> snowballstemmer==2.0.0

But you don't have `python-language-server`
So `python3.8 -m pip install python-language-server`

**Comment by jackbomb88** [comment]
> Hi,
> 
> Could you tell us what is the output of commands:
> 
> * `which flake8`
> * `flake8 --version`
> 
> Have you installed flake8 for python3.8 with taking care of pip version ?
> _i.e._ using `python3.8 -m pip install flake8`? (to test if installed: `python3.8 -m flake8 --version`)
> 
> In the options of linter-flake8 atom package, there is the path of bin flake8 to add. You should put the absolute path or adding the path of bin directory containing it in your **.bashrc** or in your **.bash_aliases**

**Comment by jackbomb88** [comment]
> Hi,
> 
> Could you tell us what is the output of commands:
> 
> * `which flake8`
> * `flake8 --version`
> 
> Have you installed flake8 for python3.8 with taking care of pip version ?
> _i.e._ using `python3.8 -m pip install flake8`? (to test if installed: `python3.8 -m flake8 --version`)
> 
> In the options of linter-flake8 atom package, there is the path of bin flake8 to add. You should put the absolute path or adding the path of bin directory containing it in your **.bashrc** or in your **.bash_aliases**

I installed flake8 using the command you gave to me and the problem is solved. Thank you.
