### ISSUE TITLE
Linter-Flake8 keeps on crashing

### ISSUE THREAD

**Issue by ghost** [AtomLinter/linter-flake8#757]
When ever I try to use Atom, I get this error message: 
```
linter-flake8:: Flake8 threw an error related to:
flake8.exceptions.PluginRequestedUnknownParameters: "pycodestyle" requested unknown parameters causing 'FileProcessor' object has no attribute 'indent_size'
Please check Atom's Console for more detail
```
I use pycodestyle 2..7.0

**Comment by renatonerijr** [comment]
I had the same problem, I installed Flake8 using apt, which installs an old version of Flake8 that conflicts with pycodestyle.

Related issue: https://github.com/PyCQA/pycodestyle/issues/983

To solve this, I removed the package and then installed it with pip, and made an alias to flake8 in bashrc
```bash
sudo apt-get remove flake8
python3 -m pip install flake8
// Alias in bashrc
alias flake8="python3 -m flake8"
```
