### ISSUE TITLE
Use setup file

### ISSUE THREAD

**Issue by knyghty** [AtomLinter/linter-flake8#8]
It would be nice if the linter could use a setup.cfg or tox.ini etc. if found in the root project directory.

Normally flake8 will read these automatically if there's one in the same directory as it is invoked from, but there is also a --config option to specify a path.

**Comment by matthewwithanm** [comment]
I can put together a PR for this; I'm just not sure of how to resolve the package settings. (Personally, I don't think there should be any package-level linter config and instead it should just rely on the normal flake8 configuration behavior.)

**Comment by matthewwithanm** [comment]
@yellottyellott @AtomLinter is actually making a copy of the file in a tmp directory, which can mess up a bunch of stuff like this. I mentioned it in AtomLinter/Linter#213 but it seems unlikely to be changed. Unfortunately, that means individual linter packages have to reimplement this kind of logic :poop:
