### ISSUE TITLE
Not loading tox.ini file

### ISSUE THREAD

**Issue by sgtsquiggs** [AtomLinter/linter-flake8#80]
linter-flake8 seems to ignore my project's tox.ini and instead only use the rules defined in Settings.

![screen shot 2015-09-18 at 11 23 30 am](https://cloud.githubusercontent.com/assets/3420325/9963160/bb7bea7e-5df7-11e5-95bb-03b826300e92.png)
![screen shot 2015-09-18 at 11 24 14 am](https://cloud.githubusercontent.com/assets/3420325/9963176/d0c0bfae-5df7-11e5-9dc7-da788bdd1e47.png)
![screen shot 2015-09-18 at 11 24 35 am](https://cloud.githubusercontent.com/assets/3420325/9963188/de196638-5df7-11e5-9d54-61be972576d1.png)

Leaving `Ignore Error Codes` blank in settings does not make a difference (thought it may be overriding, but not the case)

**Comment by Arcanemagus** [comment]
Are you sure you are running the latest version? The description for the current setting that seems to match what that is describing is _much_ shorter, so I'm wondering if when that was updated maybe the config name was changed as well?

It should take into account anything put into the `projectConfigFile` variable in the relevant section of your `config.cson`.
----
In essence all that it is doing is constructing a command option line with "--config <whatever is in that setting>", you might be linting a file that is in a sub directory and it can't handle that?

**Comment by sgtsquiggs** [comment]
flake8:
`2.4.0 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 2.7.10 on Darwin`

linter-flake8:
1.6.1


Is there a debug mode so I can see what the --config would be? I could debug this out from command line and see what's up.

**Comment by sgtsquiggs** [comment]
I believe this is the same issue as #66. Closing!

**Comment by Arcanemagus** [comment]
Ha, came back here to make sure the author of this issue knew what I discovered looking into that only to see it's the same person that caused a re-investigation :stuck_out_tongue:.

Just as an FYI, I was referring to Atom's `config.cson`. I had only looked at the code when responding here, not the release status.
