### ISSUE TITLE
Lint error if code folded

### ISSUE THREAD

**Issue by phuihock** [AtomLinter/linter-flake8#97]
Steps to reproduce:
1. Fold one or more blocks
2. Lint

You should see: TypeError: Cannot read property 'tokens' of undefined

Versions:
flake8: 2.4.1 (pep8: 1.5.7, mccabe: 0.3.1, pyflakes: 0.8.1) CPython 2.7.6 on Linux
atom: 1.0.9
OS: Ubuntu 14.04.3 LTS

**Comment by Arcanemagus** [comment]
Your Atom version is _very_ old, update that (and probably most of your packages...) and see if you are still seeing issues.

**Comment by phuihock** [comment]
Upgraded atom to 1.0.19 but same error:
TypeError: Cannot read property 'tokens' of undefined
  at extractRange (/home/phuihock/.atom/packages/linter-flake8/lib/main.coffee:59:7)
  at /home/phuihock/.atom/packages/linter-flake8/lib/main.coffee:171:22

Versions:
flake8: same version
linter-flake8: 1.9.0
linter: 1.8.1

I tried linting folded .js files with linter-jshint, no issues. If you need more info, do let me know.

**Comment by Arcanemagus** [comment]
Interesting, I couldn't reproduce this on one computer, but I now can on a different computer. Looking into the cause of this.

**Comment by Arcanemagus** [comment]
A fix is pushed out in v1.9.1, let me know if you see any further issues!

**Comment by phuihock** [comment]
Awesome. The fix works. Thanks!
