### ISSUE TITLE
Message underline breaks when code is folded

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-flake8#99]
While verifying that #98 worked properly I noticed that the message range highlighting gets broken when blocks of the code are folded.

@patrys Do you have any time to look into this? This specialized highlighting was part of #81.

Before:
![image](https://cloud.githubusercontent.com/assets/427137/10586149/a9613db0-764f-11e5-83b1-be94b5ac77c7.png)

After:
![image](https://cloud.githubusercontent.com/assets/427137/10586171/c6a21d04-764f-11e5-9d89-da0c570f8202.png)

**Comment by patrys** [comment]
Ouch! I think that's caused by screen vs buffer coordinates. Will try to fix that tomorrow.

**Comment by Arcanemagus** [comment]
It's not a breaking bug, so when you get a chance. I can look into it, but probably won't have time for a few days.
